### ISSUE TITLE
Propagate error when loading keytab

### ISSUE THREAD

**Issue by asaf** [jcmturner/gokrb5#10]
Hey,

First i'd like to say thanks for this great library (finally no conflicts between million of versions of native krb libraries!)

Is there any reason why error is not propagated in this line? making it impossible to be aware of IO problems during file read

https://github.com/jcmturner/gokrb5/blob/6aa472fbcf4ab3d72a0874a7fa4975db8671e040/keytab/keytab.go#L101

Thanks

**Comment by jcmturner** [comment]
I'm using named return values where the error is named err and the call to ioutil.ReadFile sets the value of err. Therefore the return should propagate the error. Are you experiencing a problem with it not doing this?

**Comment by asaf** [comment]
@jcmturner Ah, no, just a combination of reading the code wrong and a bug in my stack, my bad!

thanks.
