### ISSUE TITLE
ParseCCache and keytab file

### ISSUE THREAD

**Issue by keith6014** [jcmturner/gokrb5#103]
Currently, I use 

```go
b, _ := ioutil.ReadFile("krb5cc") // kinit -kt keytab_file user@DOMAIN.COM
c,_ := credentials.ParseCCache(b)
cl, _ := client.NewClientFromCCache(c)
```
this works

However, instead of using the credential cache I would like to use the keytab directly.

Is it as simple as swapping
```go
kt, err := keytab.Load("/path/to/file.keytab")
cl := client.NewClientWithKeytab("username", "REALM.COM", kt)
```
or do I have to do more?

**When I tried do it, I get a 401 Unauthorized to my web resource.**

Do I have to anything else? Looking at the code for NewClientFromCCache  I see a lot of functions being called -- https://github.com/jcmturner/gokrb5/blob/master/client/client.go#L68, but for NewClientWithKeytab (https://github.com/jcmturner/gokrb5/blob/master/client/client.go#L52), its much smaller.

**Comment by jcmturner** [comment]
You should just need to do this:
```go
// Load the keytab
kt, err := keytab.Load("/path/to/file.keytab")
if err != nil {
	return err
}
// Create the client with the keytab
cl := client.NewClientWithKeytab("username", "REALM.COM", kt)
// Load the client krb5 config
conf, err := config.Load("/etc/krb5.conf")
if err != nil {
	return err
}
// Apply the config to the client
cl.WithConfig(c)
// Log in the client
err = cl.Login()
if err != nil {
	return err
}
// Form the request
r, err := http.NewRequest("GET", url, nil)
if err != nil {
	return err
}
// Apply the client's auth headers to the request
err = cl.SetSPNEGOHeader(r, "HTTP/host.test.gokrb5")
if err != nil {
	return err
}
// Make the request
resp, err := http.DefaultClient.Do(r)
if err != nil {
	return err
}
```

**Comment by keith6014** [comment]
Thankyou. 
I assume, 
cl.WithConfig(c) means cl.WithConfig(conf) 

I get [Root cause: Networking_Error] Networking_Error: AS exachange Error: failed sending AS_REQ to KDC: [KRB Error: (24) KDC_ERR_PREAUTH_FAILED Pre-authention information was invalid]

Then
Could not get service ticket: client does not have a session for realm FOO.ORG or for the default realm FOO.ORG, login first 

Then I get the 401

**Comment by keith6014** [comment]
Not sure if it helps but when I do 
```bash
kinit -k -t keytabfile user@REALM.COM 
klist -e 

My Etype (skey,tkt): aes256-cts-hmac-sha1-96, aes256-cts-hmac-sha1-96
```

**Comment by jcmturner** [comment]
Can you share what the output of this command is:

```
klist -k keytabfile -e
```

**Comment by keith6014** [comment]
> kvno  Principal
> 15      user@REALM.COM (aes256-cts-hmac-sha1-96)
> 15      user@REALM.COM (arcfour-hmac)
>

**Comment by keith6014** [comment]
thanks for taking the time to look at this! 
I am 99% sure I set the correct password. I tried to give a wrong password in ktutil and it won't let me.
I am able to capture the traffic -- what should I look for and how should I set my filter? 
I am not sure what KDC I am using. Its using a NT domain controller I guess.
Are there any other tests I can or should run for this?

**Comment by jcmturner** [comment]
I'm curious about when you say ktutil won't let you use the wrong password. The MIT [ktutil](https://web.mit.edu/kerberos/krb5-latest/doc/admin/admin_commands/ktutil.html) does not check the password is correct, it just formats the value into a keytab file.

I have tested against an NT domain controller and I am still unable to recreate your issue.

What is the client you are trying to authenticate from? Is it time synced with NTP?

**Comment by keith6014** [comment]
Yes, sorry. you are right. It won't check if the password's validity. 
The client is a Linux host.  NTP is running on the client. 

It must be something I am doing wrong...

**Comment by jcmturner** [comment]
I'm not sure there is much more I can do on this atm. If you continue to have the issue and have more information please re-open this issue.
