### ISSUE TITLE
Questions about v1 vs v4

### ISSUE THREAD

**Issue by aokolnychyi** [jcmturner/gokrb5#116]
I have a few questions.

1. If I create a client from cache (i.e., ``credentials.LoadCCache``) but also call ``cl.WithKeytab(kt).WithConfig(cfg)`` later on. Will the ticket be automatically renewed?
2. I am upgrading from v1 to v4. I noticed a difference in the behaviour when I instantiate a client from a keytab. Right now, I have to call ``cl.Login()`` explicitly, which was not the case before. Am I correct that this is intended?

**Comment by aokolnychyi** [comment]
It looks I misinterpreted [this comment](https://github.com/jcmturner/gokrb5/blob/master/client/client.go#L67) in the source code.

I have multiple ways how to instantiate a client. In the approach below, I do not have to explicitly call ``Login()``  before ``SetSPNEGOHeader()``.

```
cfg, _ := config.Load(k.configPath)
cache, _ := credentials.LoadCCache(k.cachePath)
// instantiate a client from cache
cl, _ := client.NewClientFromCCache(cache)
// load keytab
kt, _ := keytab.Load(k.keytabPath)
// make the client aware of the keytab and config
clWithConf := cl.WithKeytab(kt).WithConfig(cfg)
...
clWithConf.SetSPNEGOHeader(request, spn)
```

Did I get you correctly that the cache will be ignored in the scenario above? Why is ``Login()`` not needed then?

**Comment by jcmturner** [comment]
Thanks, I will reword that comment as it is a little misleading. However, I'm glad it's directed you to look into this as no one wants a production outage a few hours after things seems to be working well.

In the example code you have given above I think it would work if you didn't bother setting the keytab as it will not be used. The SetSPNEGOHeader call will be using the TGT that was loaded in from the CCache. However when that TGT expires the SetSPNEGOHeader call will fail.

I would suggest not using the NewClientFromCCache, rather do the following and the TGT will be automatically renewed.

```go
// Load the keytab
kt, err := keytab.Load("/path/to/file.keytab")
if err != nil {
	return err
}
// Create the client with the keytab
cl := client.NewClientWithKeytab("username", "REALM.COM", kt)
// Load the client krb5 config
conf, err := config.Load("/etc/krb5.conf")
if err != nil {
	return err
}
// Apply the config to the client
cl.WithConfig(conf)
// Log in the client
err = cl.Login()
if err != nil {
	return err
}
// Form the request
r, err := http.NewRequest("GET", url, nil)
if err != nil {
	return err
}
// Apply the client's auth headers to the request
err = cl.SetSPNEGOHeader(r, "HTTP/host.test.gokrb5")
if err != nil {
	return err
}
// Make the request
resp, err := http.DefaultClient.Do(r)
if err != nil {
	return err
}
```

**Comment by aokolnychyi** [comment]
Thanks a lot for the clarification!
