### ISSUE TITLE
Error resolving KDC address: missing port in address

### ISSUE THREAD

**Issue by edganiukov** [jcmturner/gokrb5#12]
Hi,
by default KDC port is 88, we have a config without the port and it is works for all other our services, but not with gokrb5. So I assume it would be good to add the default port if it is not defined in krb5.conf. Here is following error:
```
 [Root cause: Networking_Error] Networking_Error: AS Exchange Error: failed sending AS_REQ to KDC: [[] Failed to communicate with KDC kdc.example.com. Attempts made with UDP (Error resolving KDC address: address kdc.example.com: missing port in address) and then TCP (Error resolving KDC address: address kdc.example.com: missing port in address)]
```

Thanks.

**Comment by jcmturner** [comment]
Thanks for raising this...
The config should now assume port 88 if one is not specified for a KDC
