### ISSUE TITLE
Creating a keytab file

### ISSUE THREAD

**Issue by keith6014** [jcmturner/gokrb5#124]
Is it possible to create a keytab file using the API? I would like to create a keytab and use it to see if it will resolve, https://github.com/jcmturner/gokrb5/issues/103

**Comment by jcmturner** [comment]
The Keytab type has a Write() method to write the bytes to an io.Writer but I don't think that is what you are meaning.

I'm not sure how creating a keytab with gokrb5 will help you with #103 ktutil can create a keytabs for your testing.
