### ISSUE TITLE
docs: additional `go get` required. Chance to use `dep` or `vgo`?

### ISSUE THREAD

**Issue by trung** [jcmturner/gokrb5#126]
Thanks for producing a great library. I'm using without any issue so far.

Just a note that there are additional `go get`s required per my experience.
```
go get gopkg.in/jcmturner/dnsutils.v1
go get gopkg.in/jcmturner/aescts.v1
go get github.com/hashicorp/go-uuid
go get github.com/jcmturner/gofork
```
Is there any chance to use `dep` or `vgo` to support dependency management?

**Comment by jcmturner** [comment]
I'm updating the readme to cover the list of ```go get``` commands. I'm looking into vgo as this seems to be the way versioning is going.

**Comment by jcmturner** [comment]
I think I'm going to wait for vgo to be production ready rather than put the effort into dep. Therefore it may take a while to get round to this.

**Comment by jcmturner** [comment]
Closing this issue and will address when vgo is ready for production use.
