### ISSUE TITLE
simple kerberized http server - example code not quite working

### ISSUE THREAD

**Issue by tokenrain** [jcmturner/gokrb5#137]
I am very new to GoLang but have been using Kerberos to protect web
sites for quite some time using the mod_auth_kerb module for Apache. We
run a fairly generic MIT Kerberos infrastructure on Linux and all of out
hosts can use netgotiate authentication to reach Keberized web sites.

I am building my first GoLang based web services and would like our
clinets to authenticate directcly to the GoLang webserver. I found your
library and was hoping that it would be simple to set a simple http
server that used Kerberos authentication.

I tried using the the code in examples/httpsServer.go but have been
unable to trouble shoot why authentication is not working. I have to
make two small modifications to the example code and it seems that
things have changed a bit and the example code has not been updated.

(1) service.SPNEGOKRB5Authenticate(th, kt, "", l) was changed to
service.SPNEGOKRB5Authenticate(th, kt, "", false, l) as this function
now seems to require and extra argument

(2) service.CREDENTIALS_CTXKEY was changed to service.CTXKeyCredentials
as it seems that the constant has changed

Using the Go code listed below with the Keytab and krb5.conf that exists
on all our servers. The following curl command fails with the server
displaying the following error

`curl --negotiate -u : -X GET http://test901.dc1.acmewidgets.net:8080/`

The client where I issue this command does obtain a Crendtial cache
keytab for the HTTP prinicipal. So I know somepart of the authentication
process is working

```
06/11/2018 20:14:20  06/12/2018 19:45:53 HTTP/test901.dc1.acmewidgets.net@ACMEWIDGETS.NET
        renew until 06/18/2018 19:45:53, Etype (skey, tkt): aes256-cts-hmac-sha1-96, aes256-cts-hmac-sha1-96

```
**The Error**

```
GOKRB5 Service: 2018/06/11 20:14:20 http.go:91: 10.103.12.64:59696 - SPNEGO Kerberos authentication failed: [Root cause: Decrypting_Error] Decrypting_Error: error extracting authenticator: error decrypting authenticator: <nil>
```
It seems that there is a decryption problem in the AP_REQ part of the
authentication chain - I just can not seem to figure out what might be
going on. We share aes256-cts-hmac-sha1-96 as a key type so I am not
sure what the issue is.

I have traced it down to DecryptAuthenticator in messages/APReq.go which
calls crypto.DecryptEncPart and that is where end failure happens

The only thing that comes to mind is that when I confiure Apache for
Kerberos auth I tell the server the prinical name that is expected on
the server side. In the Go lang example I load the Keytab but I do not
specify the princpal that should be used for the conversation.

I was hoping you could take a quick look at my example code and see if
there is something simple that I am doing wrong here.

All and any help would be greatly appreciated.

**Go Code**

```
package main

import (
        "fmt"
        "gopkg.in/jcmturner/gokrb5.v5/credentials"
        "gopkg.in/jcmturner/gokrb5.v5/keytab"
        "gopkg.in/jcmturner/gokrb5.v5/service"
        "log"
        "net/http"
        "os"
)

func main() {
        // Create logger
        l := log.New(os.Stderr, "GOKRB5 Service: ", log.Ldate|log.Ltime|log.Lshortfile)

        // Load the service's keytab
        kt, _ := keytab.Load("/var/tmp/http.keytab")

        // Create the application's specific handler
        th := http.HandlerFunc(testAppHandler)

        // Set up handler mappings wrapping in the SPNEGOKRB5Authenticate handler wrapper
        mux := http.NewServeMux()
        mux.Handle("/", service.SPNEGOKRB5Authenticate(th, kt, "", false, l))

        // Start up the web server
        log.Fatal(http.ListenAndServe(":8080", mux))
}

// Simple application specific handler
func testAppHandler(w http.ResponseWriter, r *http.Request) {
        w.WriteHeader(http.StatusOK)
        ctx := r.Context()
        fmt.Fprintf(w, "<html>\nTEST.GOKRB5 Handler\nAuthenticed user: %s\nUser's realm: %s\n</html>",
                    ctx.Value(service.CTXKeyCredentials).(credentials.Credentials).Username,
                    ctx.Value(service.CTXKeyCredentials).(credentials.Credentials).Realm)
        return
}

```
**Keytab**

```
Keytab name: FILE:/var/tmp/http.keytab
KVNO Principal
---- --------------------------------------------------------------------------
   1 HTTP/test901.dc1.acmewidgets.net@ACMEWIDGETS.NET (aes256-cts-hmac-sha1-96) 
   1 HTTP/test901.dc1.acmewidgets.net@ACMEWIDGETS.NET (arcfour-hmac) 
   1 HTTP/test901.dc1.acmewidgets.net@ACMEWIDGETS.NET (des3-cbc-sha1) 
   1 HTTP/test901.dc1.acmewidgets.net@ACMEWIDGETS.NET (des-cbc-crc) 

```

**Krb Config**

```
[libdefaults]
    default_realm   = ACMEWIDGETS.NET
    kdc_timesync    = false 
    forwardable     = true
    proxiable       = true
    ticket_lifetime = 1d 0h 0m 0s
    renew_lifetime  = 7d 0h 0m 0s

[realms]
    ACMEWIDGETS.NET = {
        kdc             = krbs002.dc1.acmewidgets.net
        kdc             = krbs003.dc1.acmewidgets.net
        kdc             = krbs001.dc1.acmewidgets.net
        admin_server    = krbs001.dc1.acmewidgets.net
    }

[domain_realm]
    acmewidgets.net = ACMEWIDGETS.NET
    .acmewidgets.net = ACMEWIDGETS.NET
    .dc1.acmewidgets.net = ACMEWIDGETS.NET

[login]
    krb4_convert     = false
    krb4_get_tickets = false

[logging]
    default      = SYSLOG:INFO:AUTHPRIV

```

**Comment by jondysinger** [comment]
I was running into similar issues. I was able to get it to work and had to make two changes. The first was that I had to specifically call out the SPN but not include the @REALM on the end in the service.SPNEGOKRB5Authenticate call.

`mux.Handle("/", service.SPNEGOKRB5Authenticate(th, kt, "HTTP/example.domain.com", false, l))`

I had been used to using HTTP/example.domain.com@DOMAIN.COM from mod_auth_kerb.

The second change I had to make was in the APReq.go file. In the DecryptAuthenticator function, for some reason my nametype was coming in as nametype.KRB_NT_SRV_INST. However, I need it to be KRB_NT_PRINCIPAL as per my keytab. If I comment out those lines and hard code the usage variable to keyusage.AP_REQ_AUTHENTICATOR then everything works.

`usage = keyusage.AP_REQ_AUTHENTICATOR`

**Comment by tokenrain** [comment]
Thanks so much for this code change. That was indeed the issue and I have created a pull request with  the very small change needed to associate nametype.KRB_NT_SRV_INST and keyusage.AP_REQ_AUTHENTICATOR so that we can use unmodified code after the merge is done. Again thanks!

**Comment by jcmturner** [comment]
Hi,

You are right the examples have been neglected and I'll need to fix that and create some integration tests to ensure they keep up in the future.

I think the SPNEGO handler wrapper should be updated to manage the @DOMAIN.COM suffix.

With regards to the name type this needs some careful investigation and a look through the RFC to make sure this is the right fix and not just something that happens to work in a specific environment.

**Comment by jcmturner** [comment]
I'm closing this issue now as I have...

* Included running the example.go in the Travis build to ensure it keeps up to date
* I have raised specific issues for the items raised here. Please follow these if you are interested:
#147
#148
