### ISSUE TITLE
Blocking send on client session cancel channel

### ISSUE THREAD

**Issue by szli** [jcmturner/gokrb5#138]
https://github.com/jcmturner/gokrb5/blob/b7336d9b230f10c8436b1a932b454ab044232e22/client/session.go#L45

I think the channel should have a buffer size 1. I observe that, the `i.cancel<-true` call blocks because the `<-s.cancel` is in the same goroutine. With buffer size 1, push will be successful, and when we poll using select, it will get the boolean.

**Comment by jcmturner** [comment]
I see it will block if the previous session has been cancelled but it will still be present in the Entries map. I think I need to remove the session from Entries as well as make this non-blocking to be safe.

**Comment by szli** [comment]
Here is my understanding. In the renewal goroutine, when timeout, it will call updateSession, and it will call cl.Login(), and it will call AddSession, and will call i.cancel<- true. All these happens in the renewal goroutine synchronously. The <-s.cancel is also in renewal goroutine.

**Comment by jcmturner** [comment]
Yes, I see. I think you're right a buffer of 1 should solve the problem.
