### ISSUE TITLE
Key usage number may not be correct for decrypting authenticator

### ISSUE THREAD

**Issue by jcmturner** [jcmturner/gokrb5#148]
***Re-Creating Issue***
Run a HTTP service using `service.SPNEGOKRB5Authenticate`
Then run this command:
`curl --negotiate -u : -X GET http://<server address>/`

***Error***
`
GOKRB5 Service: 2018/06/11 20:14:20 http.go:91: 10.103.12.64:59696 - SPNEGO Kerberos authentication failed: [Root cause: Decrypting_Error] Decrypting_Error: error extracting authenticator: error decrypting authenticator: <nil>
`
It should also be investigated why the error is coming back as `<nil>`

***Work around***

> The change I had to make was in the APReq.go file. In the DecryptAuthenticator function, for some reason my nametype was coming in as nametype.KRB_NT_SRV_INST. However, I need it to be KRB_NT_PRINCIPAL as per my keytab. If I comment out those lines and hard code the usage variable to keyusage.AP_REQ_AUTHENTICATOR then everything works.
> 
> `usage = keyusage.AP_REQ_AUTHENTICATOR`

**Comment by jcmturner** [comment]
The following is not related directly to the issue here but was discovered during testing.

It appears that curl version 7.29 does not do SPNEGO properly. It does not add the right GSS-API header.
In the wireshark output below for curl 7.29 you can see that the OID immediately within the GSS-API section is the KRB5 oid. This should be SPNEGO OID and should contain a negTokenInit. See the 2nd  output from curl 7.58 which has this.

**Curl v7.29**
```
 [truncated]Authorization: Negotiate YIICcQYJKoZIhvcSAQICAQBuggJgMIICXKADAgEFoQMCAQ6iBwMFACAAAACjggFwYYIBbDCCAWigAwIBBaENGwtURVNULkdPS1JCNaIjMCGgAwIBA6EaMBgbBEhUVFAbEGhvc3QudGVzdC5nb2tyYjWjggErMIIBJ6ADAgERoQMCAQGiggEZBIIBFbkTHsAsUdCX67Gfn
    GSS-API Generic Security Service Application Program Interface
        OID: 1.2.840.113554.1.2.2 (KRB5 - Kerberos 5)
        krb5_blob: 01006e8202603082025ca003020105a10302010ea2070305...
            krb5_tok_id: KRB5_AP_REQ (0x0001)
            Kerberos
                ap-req
                    pvno: 5
                    msg-type: krb-ap-req (14)
                    Padding: 0
                    ap-options: 20000000 (mutual-required)
                    ticket
                        tkt-vno: 5
                        realm: TEST.GOKRB5
                        sname
                            name-type: kRB5-NT-SRV-HST (3)
                            sname-string: 2 items
                        enc-part
                    authenticator
```

**Curl v7.58**
```
 [truncated]Authorization: Negotiate YIICnAYGKwYBBQUCoIICkDCCAoygDTALBgkqhkiG9xIBAgKiggJ5BIICdWCCAnEGCSqGSIb3EgECAgEAboICYDCCAlygAwIBBaEDAgEOogcDBQAgAAAAo4IBcGGCAWwwggFooAMCAQWhDRsLVEVTVC5HT0tSQjWiIzAhoAMCAQOhGjAYGwRIVFRQGxBob3N0LnRlc3QuZ
    GSS-API Generic Security Service Application Program Interface
        OID: 1.3.6.1.5.5.2 (SPNEGO - Simple Protected Negotiation)
        Simple Protected Negotiation
            negTokenInit
                mechTypes: 1 item
                    MechType: 1.2.840.113554.1.2.2 (KRB5 - Kerberos 5)
                mechToken: 6082027106092a864886f71201020201006e820260308202...
                krb5_blob: 6082027106092a864886f71201020201006e820260308202...
                    KRB5 OID: 1.2.840.113554.1.2.2 (KRB5 - Kerberos 5)
                    krb5_tok_id: KRB5_AP_REQ (0x0001)
                    Kerberos
                        ap-req
                            pvno: 5
                            msg-type: krb-ap-req (14)
                            Padding: 0
                            ap-options: 20000000 (mutual-required)
                            ticket
                                tkt-vno: 5
                                realm: TEST.GOKRB5
                                sname
                                    name-type: kRB5-NT-SRV-HST (3)
                                    sname-string: 2 items
                                enc-part
                            authenticator
```

**Comment by jcmturner** [comment]
It appears that curl is setting the SName type to kRB5-NT-SRV-HST (not kRB5-NT-SRV-INST as was mentioned in the work around). This name type was not matched to a key usage in the AP_Req.go file.

**Comment by jcmturner** [comment]
Seems the <nil> in the log line has already been fixed in master

**Comment by tokenrain** [comment]
Just wanted to say thank you for making this update. I see that you have instituted a new function to match nametypes to keyusage. At least the software that I need now works with gokrb5 without any modification. As well thanks again for writing and maintaining this codebase. It is very helpful to me in many ways.

**Comment by jcmturner** [comment]
Very pleased to hear this is working and useful for you. I appreciate you taking the time to say thanks :)
