### ISSUE TITLE
ClientClaimsInfo error parsing byte stream headers: Malformed NDR steam: Not enough bytes.

### ISSUE THREAD

**Issue by pault28** [jcmturner/gokrb5#156]
Hi,

We use this library as part of https://github.com/wintoncode/vault-plugin-auth-kerberos.

We have a working setup that accepts kerberos ticket issued on linux host. However when we run with tickets issued from our windows 10 boxes we get `ClientClaimsInfo error`. Both windows and linux machines are on the same domain.

A bit more background around the kerberos ticket generated on linux and windows:
Windows kerberos token as python string:
```
YIILIgYGKwYBBQUCoIILFjCCCxKgMDAuBgkqhkiC9xIBAgIGCSqGSIb3EgECAgYKKwYBBAGCNwICHgYKKwYBBAGCNwICCqKCCtwEggrYYIIK1AYJKoZIhvcSAQICAQBuggrDMIIKv6ADAgEFoQMCAQ6iBwMFACAAAACjggjbYYII1zCCCNOgAwIBBaETGxFCTFVFTElaQVJELk9SRy5VS6IqMCigAwIBAqEhMB8bBEhUVFAbF3ZhdWx0LmJsdWVsaXphcmQub3JnLnVro4IIiTCCCIWgAwIBEqEDAgECooIIdwSCCHOTqWc17i++LtrEf0TvdSx2QmB0t0NGxedGs/IzFz5fH6yVeosOssTB7q2WHxynv5/dtf/5kWx2sdDw9iktgvsGiUyTmTHNo7tijSmVJXhHiwXLDx6O99zORWwqNtADmtUPIsUfwAEkTuXNF+VsW6R0AoNuG4WlznCfcu9xdqnr/9GIgudkCnbNfMJ4nbIZSyEC6UqZSGakBd9wCXJ5opKpOQo19t5q0md9YPhjs6GUzebXBpvvsOKlkoskdlsExVbLPN9lhIlx9ju0J1DbUzrT6dy06unXVD4EYpLOzKVxCV5GP3r4yJltemfQrCMI2rRLEbkI0Pja79oMOp1SwWqgBkUD2qsPlyFR6Ii0qdoA57XNz2E24i8SFwaEn7ZsEq8ftFYxisfLYvJyyGUmv+gOl9PkOXuBanpwqr5ElD3kmsARABuFb7yxAV3FmiZ+H1FNVTgCGCtonWOpu/WZRv3JhBQMC06uqGNO31QRZGxCj1l9QrwlW8gVd/Z2ER0l7qG+J4ltOqHJG3CZ2RKU5bZIoN48HoLcB+NsYSkRK7i0r6krlsSS65xmwUsce1Jn/rccFW+BARfIuflRFR4Mi4ErTvtlLpsrHfY9YG2HwEzxmqPCzjP1/FP8/20XEPECbljO/oAXCtc2nFZ+cf4u0l96eyLBp+5fYsjzA8R6LsS+61L4MZjTJWC8PApUebyUSNzp+dzy3uxEk7iUEPTiJwu8CedAf7spoRvvw3pgtQjz/LD4D0wUsxxbPcVzCJJDO1z2Eu7XvS3hzZ3srD1mkAZpUmJkVtaiSEtBpyrjBd5ZpJxyOvhLe8i2Klz6ElGus9tNIJDELu58g+l1lOM4WiEzIdXRBCoHwO/DKbDABMBFmdU26TvKjNDUClMHY9z0RA9vhqtfW1ZERH4OTjZ1R5h18YzJnuF1Jo6KQqu/v+oC/Is7ara64mVvL2guJMAy3cMyZQxfPp9fJ1YSuubhou8SylaH7roNUIc3KXjSWB6aB0j6A1h5Kc6FSlzV8LKSV2cFkLwyRf8uVgyVLftYLYsmDBthkLmb1uSV21xf9e529FKQkhBtMMUdkAeMdTCXeINXrPQ60PXPU/vYjJEEgJGHiY2MwHbiwoWZPKeHnm4FvpgkfKB8MDBayT5IRp3QYE+ff1HDa3n7n1g80ydYCM4+XYs+G4tC5uuxNHTZMp1srhErzyznXlt6/YFVTOz35cSEZi6JQYdBv7apLDZe9Lbaa9bxp0V89gZHLcwvOoIuHhYakdTy7iT7FRosnDYjnAseNw3Opo1k7Lwo+ZfVqBZoLkw+YD35px22RM2KndkOQ1evBzF1q24XIFSqmjgCRqlZsHix7XlessXHesoVXJMaCS9JoHOHthGfG6kcP+i2Stmsb5EwgZd2wlAgQMAwMJjAgJNnxGW+4KL/H22qtof0apY7eAndRBrielP3t8ybqbotVVxfEdH2r6hTrzIHjrNST+2/dSo2LYmmX63tQN75QLB8p/JZcY5AcHvOdZRL7hh5TSZ0NuuKleuX+5NfW/xIBQIpF7jZzlrZCJny00KzAwnFAWGJ3y6AZYj/5/ZbLt/34kOp/F5FXi/SpEb7EYEXJ6JGHOL/65ejRRizK7q3n/hAcsOCEN7mF8QiwY80ljwEZmaHIebAKe+8xV8z8iVBcy2PKToymYGFxilchoZr3Qebi0u9CXXc49aQzm8ISQxXkcInkmPxfgV78OTDDjMWtzJbS+TsJW6i6AAFB7FlaSTVl697sQG9M0Rgnv9gUYGKjfNrLizuGdsKtJg/S/ybo0QPyd2CZCBQ7+LTkaR2VRmct5hnLM6l5YJuAg+t+dLZkrKG7+KDBWNfDlB0yNf0I7v6mi9ZSo16vHgoAIte61Clr5MNZEJ/rG2F2s5bhLh++4eTD2hTdU7Dm5O9gR4hP/7cjyXfbpZRMirNjLN/kENXla39GyHN35SXYzqbHYYm9pWMZE6vlWY8vVYYV0ZWblqRcZSw4mutzmNX6nmp6PZpEOAxuOONi4tRAvFnDEU1538ZCikxtzZXtB81JCzJVvjHcBUDx1+89SOdSU64XRJJie9r4CHmInJKlao1roiNSFOxKKSYGTBCuPXAdh4mHBcaJIf/i6kgBklgPghNpQLbwcZ6UH8Ba/i1qUnwm8lDx6dB6A9ZY15jAfsuscqufsvDbaXQQejDbSfYb1aVAvLJXi98otDM+A4f/p6G6e1XkRfQ5S/tzKRJpsx7we5br9lgPAKsDvdvDqyCEymKF/XzqOD/ior8uNhyv43IyDbUxDfOD1h1Wj1XD1g0zTS1NSoS1sWvlETMOGktr0TUQgpaO8YSaRXJpMJk8TLVT+JAijvkfhhRKx22c3+b3QZlID5DWFJO5zt7nRginejUlFOgaD2HYjLCCcxixy0rYVYvaApzP9u2YEMBqQNUV+zWSa674OhM2YsfSNw3xbt9pQt6P8qe9nKKy4yvORHaLDi+Ch6qE0j3LxTPpbEDC4fclX5zhykOXaXPoxmfXj2UrBylPAiG24lY9n+ua/qtf/w1ZNAunRzxnHGs2ecVHWSZ2EQ+CLA6VaoJzkKeX1sEjOHGTpqH3/FPPibx4VdYT9yE1rduO4nrMapMmyXEH0GrmvAQfJXfBpO9hTk94TbX4Oy5TSERf4ZQai0XsKKSI7V/WJEWP0hlgMp0BvEeqTIoOUQVNSLpd979JHWkYxf5axeEuAai/MXRpFV3WWx9AEs1yIw4RUx8lP2ijotuw7Swr3RIosII9U/sdTW+LqI3DAp88p4ZTuVNaYQm8NLfktZpfoYwIhn39j0uvuHig0Bqaw1qUNrhf4+5KCJ0ZTwLSnE8pcO2IIr3w0k5ovuMacObR50e0s1Lfgl6vtCd90zGGJCkggHJMIIBxaADAgESooIBvASCAbh5LtWE7NyyoqwdGlWqRs3Kjn67CifJjuNX0T48p/Qq3Ax+iN10ldb3OkhfUp9dDS6QhaIzTAar5q86pr8cT3XDQaQ2r+Jpx0pc6sdZj0gKgZhoaq61uPxIoz+PWg0ObW+yVAx6jIlt1+NepHe9g2qtBDEF3uu5tAyrg+X0wx89hujntg8IGsAuhfjR6D6920dPwaXKkpWWvnySDaj5Val6fTv+ncwHomtgOsUKPDhCmaIXZCG6k2r0dW0fjkU8VRhvNHMdNDrAWmUEhvDXGA3xmMcCrAxGzKsPOLEjaa7Cl2A2l4St3QG4jqTXxJVw+yNpY57OZTH/Yq2Jze8ZG8AqCuL+XyFDIdimo9jUEjjPPj8p4iaCD2Qs3dDxPaJVVD0ym55I4YJVqy8OPBUnvjjwfK5q/tdzXspvoZtoYhsJxCvxIfgVpz093Uihf4owtTKnfu2EcayNYGodRs4WmEcWST4uyskpijlMUjgfsT79F7YVPUENwCYWAS14YE2oQj22j/10ubEJtVty6QQLUHdOoBQGyZYx8rCO7FpSz69OR60atx6tyFschqZRt6IyWCvKeM6APh8RZA==
```
Linux Kerberos token as python string:
```
YIII3wYGKwYBBQUCoIII0zCCCM+gJzAlBgkqhkiG9xIBAgIGBSsFAQUCBgkqhkiC9xIBAgIGBisGAQUCBaKCCKIEggieYIIImgYJKoZIhvcSAQICAQBuggiJMIIIhaADAgEFoQMCAQ6iBwMFACAAAACjggeRYYIHjTCCB4mgAwIBBaETGxFCTFVFTElaQVJELk9SRy5VS6IqMCigAwIBAaEhMB8bBEhUVFAbF3ZhdWx0LmJsdWVsaXphcmQub3JnLnVro4IHPzCCBzugAwIBEqEDAgECooIHLQSCBynmGSUEJ/8bCMlSNosAuluhIF8o48WLkdYLE8Spq5bQR3DAB9b6k/53ocrBuZiz2CK+Kh1Tgwy6pknu3mu7YeZfYGVXtZGjCOAiuqG/LmA34zoT4JqDsL4/spv/yGGAdf0Ak8JTWhZkJ7EO+6OqW0QCmaUfO63yfkbJHdbeKc7Fs3E+484P5C0XlJv0iX0vJc1ACSdqVKs5wea+WTnlD0WLy8D4OxuxroL9AoOZ1NEkkSlHfqfQ+oCuXed0pX6KJwixWhou2EPQ9oANw80tXsrtw9fGbr58425TQ/q5BbOuqLeymsaQYMfgK13WOU0sqWsNjusvpSsYyHbw2Jk7V3s5IqLLm58TWd55ou1be8TU0TC5SHC0R3yDZf69xkH9BKsX5FNAcPZ7SDdU2Hhgj3+AGUzMH27c9vOOqRKQLXiKpvMWTFx2x3YPYVCCeeZDst8i2/i7MwGYb13y/PcglDjwd2RTTzPJ9xlpFqDdjLhgnrckU7alxBKtHViOzSqWZLTKPHOQeFljRI41i0VHswy07xFzpJT1vlhGK39W4z+37p6oh5cB9rHiuH9yJE9U2WdlVHU1kZfNZLo14lM703zOGwjwTLci0mrdp7RBCr3UlifShMbB4psPDNC67Flk+Xk1fGfE3FWpi5BLLWcosRV37Yp4+Ws2hr4pFYA9WyEHn4+mMXp20+we6cpmAn1wHRWSSeElgw6jDUpIZonih2CCpGB1+4Zy4+s7x7Qe8hRtfM/gEyP+Cu0e8FUc/8/C7Tw0bimqle8qDVISFDABs3Z74vfdJ2c5NBVjyJAuBkccRFvmYndBAMwGM8zQcBnr4RwMhAOZ8YWtcloFDu7UwJhmCP89+e7tbZTzRpEVWkx/0n/LkEAr9elyT40PLbfnuHqFvTT8LVnHTIhx+Y9rLPkd9uu+72D7Ue3cRnGpZGEc+wtGfWnSVtJT7SFYluHGhll6HiIB88xGB1UMIAXKDVrwRocUxmS8PswotOcfNAORioY7ro4V1a146ia0NulmhpJs2uIq/MO7VFrDO4zjHO8CLv/3OkQGVlP+I9v8n43E74zyyrmOK3VZZWhNEm2Bxj4ORLxNn3sDsdEF3uv3g/ex3lqq07wLStc62F9V8IT8w38AkDDVU9v0Bh8we/jbMygwygyhBT6z4XxxAsxVGyppHTMbe8b13PJEna58GtBiSI/gld1y3wrVPtUKq/+bAzZQIge+Ez0CT94I8MLfHCQes7g6pYrXS0aD0S9k/CaCPdXnDfyhaQ7AyQ5I3+HwensQpp45hGkwWzGhWvdzC16AAeQYI25ZKnrmW1PrbRaKIXCf2+HIKtrtYhi085/hA4VIkddhdL1b/xLkIbIPLx1w/ktRaGk/GFfOze8O/OrnTt3dxfi//y68lUG0C8+XetIjbcA0BWCYVxbNvNf4xC7TFSyWxW0IZ5skWJ+QGWhxC5qTj36n+QhSxERKUqJOh+6BByigkc6KW1HQpW3q335qZeJGG6OmZDy6FEVDxajvPVj1pjJSflOAywMp6/Io7wRlNYrYLgFHUe8zx//YfJUKEWGSEPqhGwtZK22Jk6ciHBz2dnh0GHLvzTTYPflXMDt8CyP3Fwvi8l9b27o+6tkxlh0Mgwx85YxEtsyQLkKQOJR3d/ENHlpL9cDR0G2TEK7BZ3FuB1NUn8TbTsmVRxUUnuyPCAR95Zth1U9xDSjU/BKAI0roehunQkKfjBiIJ5hpckLtRSlB5t5bCwRoLBEWcMXhtxJhB8gqG6xyl1nuHr8LO5ZPE8iI4evQeimq/PY8j7XFnU2kl+Lwl6rRjK4nqPAB/nFd89ZDEKPvIwUSMLpX86dbTdVrF6HSgJLhMO+YybTl9CLQOykXPiV8C7d5t52YVRb0L8RJzy6VdpB0DlRLtasRuaOi2cpQAWBVJqSJVwn0F92c9ktC6voZT0Jtyk0W8rbTboLRkNUq2B9x/M4XYrlkxoTcWD+at4beKnETxAXJKVr724SN0X/lGwnAUtVCnDFBJANj7d018tK5v63ySOxYDbcQqYF9K3oogyN2XDwMhR4c0mi5mTkJesmdoeXSbcfkAWOI/287WDPUjf0U3XmDObeL1sH/4nNJAbWhMnf9/G9KnOUyDFXkoZsKYiVqHzcIez+c1EvLmomsQkUsxqwNCtzJf6RuclirU8TNb3CGtGQXd5As0X/1Na0VVoYBJ3U2aY2FI/FKimyH5v6ZmAlOCbik8SpBkFzpxU+G4TXxiC225x9/OSgfbCOfu8QnalGXMg4/rWpTOveAAI0mW6dVoFcxs5LYj8RbQD7y/+QGGHyW5VpCkOcs+0sSo2QOdj39cJooGQjj9bPW9JhTzQhhM7gmMt+r+j4YXecBvLatq46JXmoLzugFJy92U3benVocOILqJS9HWLf3lq4Vv6ADXghHSjs+/CByu81VEMVOnTxGDKikgdowgdegAwIBEqKBzwSBzECXugJvFhLJSMcd4y6OIKkCWRcv9rvulsPOAijpzzyio1Qr80D2eXpyJ2xGYobVhhbXAN50TAKIYBEUwKxbktiN+Tu33szQUm1ltqY3++6a7DBVry/r4Crp/PtiP2FXq0C6vi7XXsT5Ezkl7908sVNdUWUkfaFcN0b4Uawvxren4OdYw3FIuUUP2HW9XomAwIuAGOMRv0dmTCeV/hgtzfe2NSm01F4tZx6GikwL95gkvMXSwl4vhHbDN5itEaWSv0dlgTweC6FRZghSpQ==
```
We will add more info once we get them. Just keen to get this going.

Thanks.

**Comment by pault28** [comment]
@jcmturner Just adding a bit of debugging to the code and I see this error:
```
'error processing ClientClaimsInfo: error parsing byte stream headers: Malformed NDR steam: Not enough bytes 0 and byte is []'
```
the `commonHeaderBytes` is empty. Any indicator of anywhere else I can put debugging to get better help?

**Comment by jcmturner** [comment]
Hi,

Can you try the code on branch "issue-156". 
https://github.com/jcmturner/gokrb5/blob/issue-156/pac/client_claims.go

A bit "trial and error" I'm afraid.

I tried to marshal the tickets you provided but they don't seem to be TGS replies.

**Comment by pault28** [comment]
@jcmturner It works!!! on both linux and windows clients. This is awesome. :)
I applied your patch against `gokrb5.v4` which the vault kerberos plugin is tied to.

**Comment by pault28** [comment]
@jcmturner - quick update. Got a different but related error this morning. See below:
```
{'errors': ['error processing CredentialsInfo: error parsing byte stream headers: Malformed NDR steam: Stream does not indicate a RPC Type serialization of version 1']}
```
This happens only when I log on to my machine using smart-card. Remoting to a server without smart card and running same code works just fine.

**Comment by jcmturner** [comment]
I've pushed another update to branch issue-156. Can you try this? 

Hopefully we can work through these issues.

Microsoft are not consistent in what is and is not NDR encoded and the documentation does not always specify what is an isn't. This has made it hard to code as I also have little to no access to test data to work against.

**Comment by pault28** [comment]
Thanks @jcmturner - Will give that a try shortly. There is a new error that will make you laugh a bit :)

```
{u'errors': [u'error processing ClientClaimsInfo: Malformed NDR steam: Non-zero
padding left over at end of data stream']}
```
From my investigation using different users in the domain, I was able to narrow the cause to number of AD groups a user belongs to. Users with high number of AD groups experience this error whilst those with a lower number of AD groups do not.

**Comment by pault28** [comment]
The able only happens from windows machine as well.

**Comment by jcmturner** [comment]
OK this is difficult to troubleshoot as I don't have any ClientClaimsInfo to test against. I think I may need an AD environment with ADFS installed (a bit of a guess as I'm not a windows expert). Let me try this and see what I can get in a test environment.

**Comment by pault28** [comment]
Thanks @jcmturner - I understand your pain but appreciate your help as well.
Got below when testing with new patch with smart card login

```
{'errors': ['error processing CredentialsInfo: error decrypting PAC Credentials Data: error decrypting: integrity verification failed']}
```
every thing else still works as last reported.

**Comment by jcmturner** [comment]
I'm working on getting an Active Directory set up that will send me some client claims info. So far I've managed to get it so send me some but its zero in size. I'll keep working on it and then I'll have some data to test against.

**Comment by jcmturner** [comment]
I think I have fixed the ClientClaimsInfo issue you were having on branch "issue-156". It was a bit of a rabbit hole ;)

I now need to figure out the CredenitalsInfo one.

**Comment by jcmturner** [comment]
I looked further into the CredentialsInfo issue. It seems that this is only needed in order to support RFC4556 which gokrb5 has not yet implemented (#158 has been raised for this). However I don't think you need RFC4556 for what you are doing so you just happened to be running into something which wasn't quite right but you don't need and wouldn't work for any one any way.

Therefore I have disabled trying to parse the CredentialsInfo so you should not have this error any more.

I think what is on branch "issue-156" should resolve all the problems you have reported. Can you test with that and let me know. If it all works I'll get it merged in an a new release created.

**Comment by pault28** [comment]
I used issue-156 branch, however I get below on all windows kerberos tickets.
```
{'errors': ['[Root cause: Decrypting_Error] Decrypting_Error: error extracting authenticator: error decrypting authenticator: error decrypting:ity verification failed']}
```

**Comment by pault28** [comment]
Please disregard the comment above. seems the branch was overridden when I was running make build. trying again.

**Comment by pault28** [comment]
@jcmturner Can I ask for a favor please? Can you port the changes to branch created from v4.1.2? It's just that the vault kerberos plugin is tied to v4.1.2 making a bit tedious for me to get a working build of it with the changes in issue-156. 
When the changes were a few files it was easy for me to port the changes and run `make`. Thanks. 
I will keep trying and report back.

**Comment by pault28** [comment]
The successful build I made with the patch gave error on windows authentication.
```
{u'errors': [u'error processing ClientClaimsInfo: error parsing byte stream headers of CLIENT_CLAIMS_INFO: Malformed NDR steam: Not enough bytes.']}
```
The only code that works so far windows is https://github.com/jcmturner/gokrb5/commit/1876a7e93fade557293bb8a73d1e370ee906b58d and 
https://github.com/jcmturner/gokrb5/commit/ec0a0bb40ad05bb6630003e5a95756ee57722621 combined.

**Comment by jcmturner** [comment]
Hi, I have investigated further and committed some new code to issue-156. Would you mind testing and see if this works for you? With regards to back porting to v4 I would prefer not to as this would be a lot of work on an old version. I am thinking of putting a PR into wintoncode/vault-plugin-auth-kerberos to up it to version 5.

**Comment by pault28** [comment]
Hi, am on vacation at the moment. Should be able test it on Monday. Many thanks.

**Comment by pault28** [comment]
@jcmturner - This is failing to build with the vault kerberos plugin:
PS - I am referencing the master branch of ndr in https://github.com/jcmturner/rpc/tree/master

```
--> linux/arm64 error: exit status 2
Stderr: # github.com/wintoncode/vault-plugin-auth-kerberos/vendor/gopkg.in/jcmturner/gokrb5.v4/mstypes
vendor/gopkg.in/jcmturner/gokrb5.v4/mstypes/claims.go:115:53: multiple-value ndr.ReadUniDimensionalConformantArrayHeader() in single-value context
vendor/gopkg.in/jcmturner/gokrb5.v4/mstypes/claims.go:127:53: multiple-value ndr.ReadUniDimensionalConformantArrayHeader() in single-value context
vendor/gopkg.in/jcmturner/gokrb5.v4/mstypes/claims.go:154:52: multiple-value ndr.ReadUniDimensionalConformantArrayHeader() in single-value context
vendor/gopkg.in/jcmturner/gokrb5.v4/mstypes/claims.go:167:53: multiple-value ndr.ReadUniDimensionalConformantArrayHeader() in single-value context
vendor/gopkg.in/jcmturner/gokrb5.v4/mstypes/claims.go:183:51: multiple-value ndr.ReadUniDimensionalConformantArrayHeader() in single-value context
vendor/gopkg.in/jcmturner/gokrb5.v4/mstypes/claims.go:208:51: multiple-value ndr.ReadUniDimensionalConformantArrayHeader() in single-value context

```

**Comment by pault28** [comment]
Please ignore the last comment @jcmturner. Just realized my working copy of issue-156 is outdated. Will update back.

**Comment by pault28** [comment]
Hi @jcmturner - I get a different type of error on windows irrespective on of the way I authenticate.
```
Jul 17 11:03:48 VAULT-APP1 vault[28617]: 2018-07-17T11:03:48.075Z [TRACE] auth.plugin.auth_plugin_4b442c61.kerberos-auth-plugin: handle request: transport=gRPC path=login status=finished err="[Root cause: Decrypting_Error] Decrypting_Error: error extracting authenticator: error decrypting authenticator: error decrypting: integrity verification failed" took=6.04208ms
Jul 17 11:04:04 VAULT-APP1 vault[28617]: 2018-07-17T11:04:04.259Z [DEBUG] rollback: attempting rollback: path=secret/
Jul 17 11:04:04 VAULT-APP1 vault[28617]: 2018-07-17T11:04:04.259Z [DEBUG] rollback: attempting rollback: path=auth/ldap/
Jul 17 11:04:04 VAULT-APP1 vault[28617]: 2018-07-17T11:04:04.259Z [DEBUG] rollback: attempting rollback: path=sys/
Jul 17 11:04:04 VAULT-APP1 vault[28617]: 2018-07-17T11:04:04.259Z [DEBUG] rollback: attempting rollback: path=identity/
Jul 17 11:04:04 VAULT-APP1 vault[28617]: 2018-07-17T11:04:04.259Z [DEBUG] rollback: attempting rollback: path=cubbyhole/
Jul 17 11:04:04 VAULT-APP1 vault[28617]: 2018-07-17T11:04:04.259Z [DEBUG] rollback: attempting rollback: path=auth/token/
Jul 17 11:04:04 VAULT-APP1 vault[28617]: 2018-07-17T11:04:04.259Z [DEBUG] rollback: attempting rollback: path=auth/kerberos/
Jul 17 11:04:04 VAULT-APP1 vault[28617]: 2018-07-17T11:04:04.260Z [TRACE] auth.plugin.auth_plugin_4b442c61.kerberos-auth-plugin: handle request: transport=gRPC path= status=started
Jul 17 11:04:04 VAULT-APP1 vault[28617]: 2018-07-17T11:04:04.260Z [TRACE] auth.plugin.auth_plugin_4b442c61.kerberos-auth-plugin: handle request: transport=gRPC path= status=finished err="unsupported operation" took=378.875µs
```

**Comment by pault28** [comment]
@jcmturner, if you don't mind, are you available for a chat regarding this on Skype? My skype id is ptinagbedia. I have sent a request to Jon Turner today....hopefully that's you.

**Comment by pault28** [comment]
That’s perfectly fine @jcmturner. 

The error is server side as we only use it for server side authentication.

**Comment by jcmturner** [comment]
@pault28 I have merged a fix for #168 into master. Can you test to see if this resolves your issue? I'll then look to create a new release. Thanks

**Comment by pault28** [comment]
Thanks @jcmturner - I will get this a test and report back.

**Comment by pault28** [comment]
@jcmturner - I did a quick test this evening with the fix from #168 which seems to work. I will validate all of the other errors are gone too first thing tomorrow (ie works with smart card and users with many AD groups). Thanks.

**Comment by pault28** [comment]
@jcmturner - all good here. Works for smart card and users with many AD groups.  I will keep an eye for the new release. Thanks once more.

**Comment by jcmturner** [comment]
@pault28 thanks for confirming. I have now issued release 5.3.0 with this included. I'm working on a PR to https://github.com/wintoncode/vault-plugin-auth-kerberos to upgrade it to this version of gokrb5.
