### ISSUE TITLE
Correct way to shutdown client

### ISSUE THREAD

**Issue by touch-head-optimistically** [jcmturner/gokrb5#159]
hi ~

I have inited a client in each go routine because I'd like to check series users but I didn't found a function to close them.

I'm suffering from memory cache problems due to creating too many clients.

```
goroutine profile: total 21618
21591 @ 0x42d4fc 0x42d5ee 0x44aaf0 0x9dd609 0x45c021
#	0x44aaef	time.Sleep+0x12f									/usr/local/go/src/runtime/time.go:65
#	0x9dd608	gopkg.in/jcmturner/gokrb5.v2/client.(*Client).enableAutoSessionRenewal.func1+0x38	/Users/.../src/gopkg.in/jcmturner/gokrb5.v2/client/session.go:58
```

```
// NewKrb5Client inits a new krb5 client.
func NewKrb5Client() error {
	cfg, err := config.Load(Krb5Conf)

	cl := client.NewClientWithPassword(name, anyalarm, password)
	cl.WithConfig(cfg)
       
        err = cl.Login()
        if err!=nil{
               //xx
        }
	return nil
}
```

As above, is there anyway that I can shutdown or close this client?

**Comment by jcmturner** [comment]
There is currently no way to shutdown a client. This was not a use case I had anticipated but it sounds reasonable.

**Comment by jcmturner** [comment]
I think this should just be a case of cancelling the auto renewal and letting the Go garbage collector sort out the rest.

This means having a method that can be called to send the message on the cancel channel.

Proposing
- Client.Destroy() method on the client that will:
    - Call sessions.Cancel() - calls session.Cancel() on each session
- session.Cancel() will:
    - send a message on the session's cancel channel to stop the auto renewal routine
    - set the EndTime, RenewTill and SessionKeyExpiration to the current time
