### ISSUE TITLE
Error decrypting AP_REQ authenticator: integrity verification failed

### ISSUE THREAD

**Issue by asaf** [jcmturner/gokrb5#168]
Hey,

Using latest code with an attempt to validate a SPNEGO token sent by an IE11 client: `ValidateAPREQ`:

> integrity verification failed

(caused by _rfc3961/encryption.go:VerifyIntegrity_)
it fails on the authenticator decryption part.

Using osx clients such kinit / chrome works just fine.

After investigation, the difference is as follows:

- IE11 sends a MechType.APReq.Ticket.SName.NameType with value 2
- Curl sends a MechType.APReq.Ticket.SName.NameType with value 3

This value propagates all the way to `rfc3961.DeriveRandom` that generates a value that causes `DecryptMessage: e.VerifyIntegrity` to fail.

I have workaround this by forcing _NameType = 3_ that make things work okay, so the code block in _ValidateAPREQ_ is such:

```golang
        var creds credentials.Credentials
	err := APReq.Ticket.DecryptEncPart(kt, sa)
	if err != nil {
		return false, creds, krberror.Errorf(err, krberror.DecryptingError, "error decrypting encpart of service ticket provided")
	}
        // workaround for https://github.com/jcmturner/gokrb5/issues/168
	APReq.Ticket.SName.NameType = 3
	a, err := APReq.DecryptAuthenticator(APReq.Ticket.DecryptedEncPart.Key)
	if err != nil {
		return false, creds, krberror.Errorf(err, krberror.DecryptingError, "error extracting authenticator")
	}
```

Thanks.

Many thanks.

**Comment by asaf** [comment]
I use:

revision = "5502bb09507bcc91e28c9b6feba046beb2e007d1"
version = "v5.2.0"

**Comment by jcmturner** [comment]
Thanks for confirming the version. Are you able to share any details about the value of MechType.APReq.Ticket.SName.NameString that IE11 is passing?

**Comment by jcmturner** [comment]
After reading this section of the RFC again: https://tools.ietf.org/html/rfc4120#section-6.2

It seems that I cannot rely on the name type value. Therefore I think I just need to update the function below to look for ``krbtgt`` as the first element in the principal name. If it is found then the key usage is ``TGS_REQ_PA_TGS_REQ_AP_REQ_AUTHENTICATOR`` for anything else it is ``AP_REQ_AUTHENTICATOR``

https://github.com/jcmturner/gokrb5/blob/64f77597640d51b8b75e4f1c0e4b4d6a2c238ffd/messages/APReq.go#L98

**Comment by asaf** [comment]
@jcmturner alright, let me know once you patch the code base so I will give it a try.

**Comment by jcmturner** [comment]
@asaf I have merged into master what I think should fix this. I have not created a new release yet. Are you able to try with this and let me know if it works for you? Thanks.

**Comment by jcmturner** [comment]
I have issued release 5.3.0 that I think will resolve this. Can you test and confirm? Thanks.

**Comment by asaf** [comment]
@jcmturner I think it's working, i'm giving it few days more in testing, will close if resolved.

**Comment by jcmturner** [comment]
@asaf are things still good? Can this issue be closed?

**Comment by jcmturner** [comment]
@asaf can this issue be closed now? Thanks.

**Comment by asaf** [comment]
@jcmturner closing for the time being, we'll be doing profound testings during the next month, if something will popup i'll re-open, thanks!
