### ISSUE TITLE
default_realm should not be mandatory in configuration

### ISSUE THREAD

**Issue by natxo** [jcmturner/gokrb5#171]
You can always specify other configuration files using environment variables or inline templating in the go code.

See http://web.mit.edu/kerberos/krb5-1.12/doc/admin/conf_files/krb5_conf.html for all the details.

Additionally, the usage of the 'default realm' relation should not be compulsory (according to the info the mit kerberos site), and the usage of dns_lookup_realm should be obeyed. Right now I need to specify c.LibDefaults.DNSLookupKDC = true 
even though in my krb5.conf which I load manually in the go program I have this variable set.

```
default_realm
    Identifies the default Kerberos realm for the client. Set its value to your Kerberos realm. If this value is not set, then a realm must be specified with every Kerberos principal when invoking programs such as kinit.
```

**Comment by jcmturner** [comment]
gokrb5 has been written to be platform agnostic library so I don't want to default to a unix/Linux file location. The code using the library can implement that logic if it makes sense to them.

The point you make about default_realm is valid so I'm going to rename this issue for that.

**Comment by natxo** [comment]
maybe if we do not see it as a 'default' but as a 'fallback' (result is the same, ease of use to the end user or application developper) then you could reconsider this choice. Seeing the library honour the environment variables would be awesome as well (and those are not only unix/linux, mit kerberos is for Windows as well).

**Comment by natxo** [comment]
come to think of it, KRB5_TRACE would be awesome too ;-)

**Comment by jcmturner** [comment]
the default_realm configuration is now optional and is only used if no realm is specified. This has been merged into master and I'll create a new release shortly that will contain this.

**Comment by jcmturner** [comment]
This is now in release 5.3.0 so I'm going to close this issue. Thanks for helping make gokrb5 better! :)
