### ISSUE TITLE
NewClientFromCCache fails after a call to kinit -R 

### ISSUE THREAD

**Issue by ragansa** [jcmturner/gokrb5#172]
Go Version: 10.2
gokrb5 version: 7b8d6d34cee695591dbaa854c72d0d9b2ebb55e8
Running on Mac OS

Building a `NewClientFromCCache` works great from a fresh `kinit`, however, if the user runs `kinit -R` Calls to NewClientFromCCache fail with:
`Failed to get token with cache: TGT not found in CCache`

Digging around, the only change I can see in the ccache is that the Server NameType goes from a 2 (when things are working) to a 1
```
  "Server": {
        "Realm": "#######",
        "PrincipalName": {
          "NameType": 2,   <---- becomes a "1" when building a ccache after `kinit -R`
          "NameString": [
            "krbtgt",
            "#####"
          ]
        }
 },
```

I see that we reject Principals if the NameTypes don't match: https://github.com/jcmturner/gokrb5/blob/7b8d6d34cee695591dbaa854c72d0d9b2ebb55e8/types/PrincipalName.go#L38-L39

Looking at the RFC, NameTypes shouldn't be used to indicate equivalence:
https://tools.ietf.org/html/rfc4120#section-6.2

I, for the sake of experimenting, tried to see if removing the NameType check would fix the issue, but instead of the `TGT not found inCCache`, I got a `KRB_AP_ERR_BAD_INTEGRITY` error.

Not sure where to go from here, is something we can fix?

**Comment by gregprosser** [comment]
(I work with @ragansa and am helping him unpack this)

From a kerberos POV, other things (like for example ssh) seem to be able to use this krbtgt/ to get service tickets despite it being the wrong NameType, so it's still "working".  I suspect this is a MacOS bug (kinit -R shouldn't be mangling that type), but I suspect the library is being too strict in enforcing it like this?

This enforcement of NameType seems pretty heavily baked into the library (it's encoded in PrincipalName.Equals()), what are your thoughts on somehow correcting this implementation to be more loose?

**Comment by jcmturner** [comment]
Thanks both for the analysis here. As you have spotted in the RFC it states:
``It [name type] is not significant when checking for equivalence.``

Therefore I shall update this:
https://github.com/jcmturner/gokrb5/blob/7b8d6d34cee695591dbaa854c72d0d9b2ebb55e8/types/PrincipalName.go#L37
to not check the nametype value.

Then I'll look into why if this is not checked in the Equal method why the TGT is not found in the cache.

**Comment by jcmturner** [comment]
Can you share some more details on the steps to re-create the ``KRB_AP_ERR_BAD_INTEGRITY`` error?

I have removed the check of the name type.

**Comment by ragansa** [comment]
Actually, I must've inadvertently made some other changes that were causing the 2nd issue (the KRB_AP_ERR_BAD_INTEGRITY), I did a fresh pull from your latest merge with the removal of name type and that has fixed our issue!

Thanks!  Appreciate your help, and thank you again for this library!

**Comment by jcmturner** [comment]
Excellent, glad we got it fixed. Thanks for replying and closing the issue.
