### ISSUE TITLE
domain name was changed in release 5.2

### ISSUE THREAD

**Issue by asaf** [jcmturner/gokrb5#195]
Hey,

Having AD realm such _FOO.COM_, in previous releases after decoding SPNEGO token the `credentials.Realm` object was resolved to _FOO.COM_ while in latest releases it was changed to _FOO_.

Just wanted to verify that this is the expected behaviour, if so then we can close this,

Thanks.

**Comment by jcmturner** [comment]
@asaf you are right this does not look correct. I think it is because of the lines below but they were introduced  in v1.1.3

https://github.com/jcmturner/gokrb5/blob/f5b5d035fe8c9212b223058a3a8c22c099e623cf/credentials/credentials.go#L125-L127

**Comment by asaf** [comment]
@jcmturner easy to fix :)

**Comment by jcmturner** [comment]
v6.0.1 has a fix for this.
