### ISSUE TITLE
gokrb5.v5: error processing realms section: v4 configurations are not supported in Realms section

### ISSUE THREAD

**Issue by sbinet** [jcmturner/gokrb5#196]
hi there,

I haven't looked too deep into this but one of my user couldn't authenticate (through CCache) because the (CERN operated) cluster he's working from has this section in the `/etc/krb5.conf` file:

```
[realms]
# Start of puppet output for CERN.CH
 CERN.CH  = {
  default_domain = cern.ch
  kpasswd_server = cerndc.cern.ch
  admin_server = cerndc.cern.ch
   kdc = cerndc.cern.ch
    v4_name_convert = {
     host = {
        rcmd = host
     }
   }
 }
```

this returns the error from the title of this issue:
`error processing realms section: v4 configurations are not supported in Realms section`

testing this locally on a test machine, I also get the error, then modifying the `realms` section with:
```
[realms]
# Start of puppet output for CERN.CH
 CERN.CH  = {
  default_domain = cern.ch
  kpasswd_server = cerndc.cern.ch
  admin_server = cerndc.cern.ch
   kdc = cerndc.cern.ch
#    v4_name_convert = {
#     host = {
#        rcmd = host
#     }
#   }
 }
```

"fixes" it.

I guess what I am asking is:
- is it a "robust" workaround? (what could break?)
- is there anything we could do from the `gokrb5` side to perhaps better handle this situation?

**Comment by jcmturner** [comment]
@sbinet commenting out the section will not cause any issues for gokrb5 but I can't comment on what effect this may have on anything else you have that may be using the ``/etc/krb5.conf`` file.

The parsing of the krb5 config returns an error for the v4 elements to ensure it is clear that they will have no effect. However I could just have the parser ignore then silently.

What do you think? Explicit error or silent ignore?

**Comment by sbinet** [comment]
I would go with an explicit error that *I* can ignore, as long as I also get a valid `credentials.CCache` back :)

**Comment by jcmturner** [comment]
Version 6.0.1 has improved this. You can use type assertion to check for an error but ignore ones of type ``config.UnsupportedDirective`` 

```
cfg, err := config.Load("/path/to/config/file")
if err != nil {
    if _, ok := err.(config.UnsupportedDirective); !ok {
        panic(err)
    }
}
```

**Comment by sbinet** [comment]
thanks! I confirm migrating to `v6.0.1` (and handling `config.UnsupportedDirective`) fixed the issue I had on CERN's cluster.

thanks a lot for the low latency of fixing issues :)
