### ISSUE TITLE
Can support tcp request？

### ISSUE THREAD

**Issue by yuxiangdo** [jcmturner/gokrb5#2]
Can the library support tcp request？I wan‘t to use gokrb5 to connect kafka，can you give me a test sample？Thank you very much.

**Comment by jcmturner** [comment]
The client will use UDP and TCP to connect to the KDC in accordance with this config: https://web.mit.edu/kerberos/krb5-latest/doc/admin/conf_files/krb5_conf.html. If udp_preference_limit is set to 1 then TCP is always used. 

In terms of talking to a kerberised service the only thing implemented so far is HTTP SPNEGO which obviously uses TCP.

Please note that gokrb5 is still very much a work in progress and more testing needs to be done. Nevertheless I'd be very interested to get some details on how you use it.

Thanks!

**Comment by jcmturner** [comment]
Hi, there was a bug in the client code when using TCP to talk to the KDC. This should now be fixed.

**Comment by jcmturner** [comment]
Hi, I don't know anything about the interface kafka provides to integrate with authentication mechanisms like this. You can see in the README.md details about how to configure a client to interact with the KDC to login, get service tickets and form an AP_REQ to send to the service side. There are also details on the serivce.ValidateAPREQ method that can be used on the service side to validate the AP_REQ sent by the client.

**Comment by yuxiangdo** [comment]
https://github.com/Shopify/sarama/pull/729
go kafka client cannot support kerberos，someone use SASL2 library，can use your library to solve the problem？

**Comment by wonderflow** [comment]
@jcmturner  hi, kafka's mechanisms is something like this https://github.com/Shopify/sarama/blob/master/broker.go#L871.

When establish a new tcp session, firstly client talk with kafka broker with an authrized token, and if the token was checked ok by kafka broker, then client can use this tcp connection to continue.

So, Can you give some guide of how to use this library to go through the kerberized kafka broker?

Thanks.
