### ISSUE TITLE
unsupported EType error

### ISSUE THREAD

**Issue by AnirudhVyas** [jcmturner/gokrb5#202]
```
SASL handshake: [Root cause: Encrypting_Error] KRBMessage_Handling_Error: TGS Exchange Error: failed to generate a new TGS_REQ < Encrypting_Error: error getting etype to encrypt authenticator: unknown or unsupported EType: 1
```

I am guessing I get this error because DES3CBCCRC is not implemented, I am not sure what am I missing other than this - here is my client initialization code - 
```
ccache, err := credentials.LoadCCache("/tmp/krb5cc_72438")
	log.Printf("ccache loaded : %+v\n", ccache)
	if err != nil {
		panic(err)
	}
	// krb "gopkg.in/jcmturner/gokrb5.v5/client"
	//cl := krb.NewClientWithPassword("user", "REALM.COM", "pwd")
	cl, err := krb.NewClientFromCCache(ccache)
```

**Comment by jcmturner** [comment]
I think this is because your TGT in the CCache is of enctype 1 DES3CBCCRC which is not supported. You can confirm this with ``klist -e ``. This is a weak encryption type so probably not good to be using that type any way. You can probably fix this by updating your krb5.conf to only have stronger encryption types specified.

Is there a particular reason you are using the OS CCache rather than logging in within your Go code?

**Comment by AnirudhVyas** [comment]
well this is a test for me personally, The bug that i posted is related to colinmarc/hdfs which uses gokrb5 lib to do stuff, when I run klist -e I get - 
```
icket cache: FILE:/tmp/krb5cc_72438
Default principal: portal-admin@BLAH.COM

Valid starting     Expires            Service principal
09/17/18 14:49:27  09/18/18 14:49:27  krbtgt/BLAH.COM@BLAH.COM
	renew until 09/21/18 14:49:27
[portal-admin@BLAH gohdfs-v2.0.0-linux-amd64]$ klist -e
Ticket cache: FILE:/tmp/krb5cc_72438
Default principal: portal-admin@BLAH.COM

Valid starting     Expires            Service principal
09/17/18 14:49:27  09/18/18 14:49:27  krbtgt/BLAH.COM@BLAH.COM
	renew until 09/21/18 14:49:27, Etype (skey, tkt): des-cbc-crc, des3-cbc-sha1
```
I would be using their binary to do ls which in turn uses krb5 - if we need to add the type (I do not own certificate issuing auth in this case, if they support the auth, I'd add it (worth a try, will do and update here). But if I cannot I might end up added an implementation - either me or one of my colleagues my send a PR your way.

**Comment by Shastick** [comment]
Hello @AnirudhVyas, 

I'm happy to encounter a prospective user of colinmarc's hdfs library!

The error you see is related to Kerberos specifically, and not the go hdfs client: 

How you initialise your credential cache (probably doing a `kinit`) results in credentials for which encryption types using `DES` are used (as suggested by `Etype (skey, tkt): des-cbc-crc, des3-cbc-sha1` in your pasted text above).

You can change the encryption types that are used by updating your `krb5.conf` file (and ensuring your KDC supports these types as well).

The README on https://github.com/jcmturner/gokrb5 shows a list of supported encryption types.

**Comment by jcmturner** [comment]
@AnirudhVyas have you resolved your problem? I don't see an issue here with gokrb5. I propose we close this issue...
