### ISSUE TITLE
MechToken init comparison issue

### ISSUE THREAD

**Issue by asaf** [jcmturner/gokrb5#204]
Hey,

I am failing [on this validation](https://github.com/jcmturner/gokrb5/blob/master/service/authenticator.go#L83), 

While OID is expected to be `1.2.840.113554.1.2.2` the list returned from AD is:

`[1.2.840.48018.1.2.2 1.2.840.113554.1.2.2 1.3.6.1.4.1.311.2.2.30 1.3.6.1.4.1.311.2.2.10]`

So equality fails,

This happens on multiple domains,

Also related to [https://github.com/jcmturner/gokrb5/pull/203](PR)

Thanks

**Comment by jcmturner** [comment]
I have merged in #203 which I think should address this. I still need to create a release that contains this.

**Comment by asaf** [comment]
@jcmturner seem to be ok now,

(now closing for a reminder to release this)

thanks!

**Comment by jcmturner** [comment]
New release v6.0.2 now includes this.

**Comment by asaf** [comment]
@jcmturner 👍
