### ISSUE TITLE
KDC_ERR_PREAUTH_FAILED after certain amount of time

### ISSUE THREAD

**Issue by sjokoladefoged** [jcmturner/gokrb5#209]
Hi,
Everything works perfect for approximately 24 hours, after that period the following error starts to appear. 
`could not get service ticket: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (24) KDC_ERR_PREAUTH_FAILED Pre-authentication information was invalid` 
After restarting the service everything works normal again. 
Any help is appreciated.

**Comment by jcmturner** [comment]
Thanks for raising this issue. I believe this is because the client's krb5.conf has an enctype that the KDC does not support and the client is trying to use this during the renewal of a TGT and failing when the KDC rejects it. The client should be able to handle this so I've worked on this and will be creating a release shortly that addresses it.

**Comment by sjokoladefoged** [comment]
Thanks for the reply - the krb5.conf contains no default enctype's, clients config is similar to below
````
[libdefaults]
    default_realm = ATHENA.MIT.EDU

[realms]
    ATHENA.MIT.EDU = {
        kdc = kerberos.mit.edu
        kdc = kerberos-1.mit.edu
        admin_server = kerberos.mit.edu
    }
    EXAMPLE.COM = {
        kdc = kerberos.example.com
        kdc = kerberos-1.example.com
        admin_server = kerberos.example.com
    }

[domain_realm]
    .mit.edu = ATHENA.MIT.EDU
    mit.edu = ATHENA.MIT.EDU
````

**Comment by jcmturner** [comment]
@sjokoladefoged I've just released v6.0.2 which has some fixes that may resolve this for you. Can you test and confirm?

If this does not resolve it I'll need some more detail on the code you have. Also I'm not sure the krb5.conf you have posted is the one you'd be using as that is the default config from the MIT krb5kdc package so doesn't contain any config for your specific domain.

**Comment by sjokoladefoged** [comment]
Hi, I tried it out now, it doesn't fail anymore - it hangs. Works normally for the same amount of time as before, but then the requests hangs while authenticating.

**Comment by jcmturner** [comment]
@sjokoladefoged thanks for checking on this for me. I was able to reproduce the hanging issue and develop a fix.

Can you try with v6.0.5?

**Comment by sjokoladefoged** [comment]
@jcmturner once again:
Failed to set SPNEGO Header reason: [could not get service ticket: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (24) KDC_ERR_PREAUTH_FAILED Pre-authentication information was invalid]

**Comment by sjokoladefoged** [comment]
I've been sick - sorry for the late response. The version is double checked, as the newest one, i'll get a tcpdump done next week when I am back in the office.

**Comment by jcmturner** [comment]
Hi, were you able to get the tcpdump?

**Comment by sjokoladefoged** [comment]
Sorry, I haven't had time yet, currently waiting the 24 hours for the renegotiate to happen and then I will get it done.

**Comment by jcmturner** [comment]
Hi @sjokoladefoged were you able to investigate here? thanks.

**Comment by sjokoladefoged** [comment]
Not seeing anything from the tcpdump inside the container - I will let it run on my laptop the coming week and hopefully get something clear there.

**Comment by sjokoladefoged** [comment]
Did the TCP dump though I think the error is different, I will get a look at it later.

**Comment by jcmturner** [comment]
Hi @sjokoladefoged on the AS_REQs can you see in wireshark if they have the preauth PA data. You should find it at...
```
Kerberos
    as-req
        pvno: 5
        msg-type: krb-as-req (10)
        padata: 2 items
            PA-DATA PA-ENC-TIMESTAMP
                padata-type: kRB5-PADATA-ENC-TIMESTAMP (2)
                    padata-value: ...
                        etype: eTYPE-AES256-CTS-HMAC-SHA1-96 (18)
                        kvno: 1
                        cipher: ...
```

If the PA data is there. What is the etype value? Does this value match what is found in the very first AS_REQ that is sent and accepted when you first start the process?

Do you have the machine that this is running on using NTP for time sync?

**Comment by sjokoladefoged** [comment]
hi @jcmturner - I hope this is sufficient
![kerb](https://user-images.githubusercontent.com/7021689/52238081-73ee9b00-28cb-11e9-9666-3db98d6da2b9.png)
Those are the requests
---
Time Sync should be here:
![time](https://user-images.githubusercontent.com/7021689/52238116-879a0180-28cb-11e9-9a25-333c62f2b6f9.png)

---

**Comment by jcmturner** [comment]
@sjokoladefoged this is interesting. For some reasons there are two kRB5-PADATA-ENC-TIMESTAMP entries in the failing request. This does not look right and a something for me to look into. Thanks for providing the info.

**Comment by jcmturner** [comment]
@sjokoladefoged is there an AS_REQ just before the one that you posted above that gets a  KDC_ERR_PREAUTH_FAILED response from the KDC?

That is you see this order of messages:
AS_REQ
KRB Error: KDC_ERR_PREAUTH_FAILED
AS_REQ

Does the first of these AS_REQs have two kRB5-PADATA-ENC-TIMESTAMP in the PA_DATA?

**Comment by sjokoladefoged** [comment]
Hi @jcmturner - yea it looks so.
![krb_asreq](https://user-images.githubusercontent.com/7021689/52434460-a7ba0280-2b0f-11e9-8f9c-0bde951e5d1f.png)

**Comment by jcmturner** [comment]
@sjokoladefoged thanks for the info. I've made a change that will prevent the two kRB5-PADATA-ENC-TIMESTAMP in the PA_DATA. However I don't think this will resolve the problem of the pre-auth failure.

Really struggling to figure out what is going on here. 

Is anything changing the password of the account between the time of the very first AS_REQ that works and the later AS_REQs that fail?

**Comment by sjokoladefoged** [comment]
Nothing is changing, only thing is the ticket expiring.. If it was a timing issue I assume restarting the issue wouldn't make a difference since the time comes from the host..

**Comment by jcmturner** [comment]
@sjokoladefoged I ran a long running client to double check and I am still unable to recreate your issue.
You can see the client code at https://github.com/jcmturner/gokrb5/blob/master/examples/longRunningClient.go

I am running this against my test KDC which is a docker container run with this command:
```
docker run -d -h kdc.test.gokrb5 -v /etc/localtime:/etc/localtime:ro -p 88:88 -p 88:88/udp -p 464:464 -p 464:464/udp --name krb5kdc jcmturner/gokrb5:kdc-centos-default
```
The screenshots below show the AS_REQ that occurs after a long wait for the tickets to expire succeeding with pre-auth:
![screenshot from 2019-02-10 11-10-41](https://user-images.githubusercontent.com/10795321/52533050-12448b80-2d26-11e9-9556-c048adb2f9e3.png)

This is the request's PA_DATA:
![screenshot from 2019-02-10 11-11-25](https://user-images.githubusercontent.com/10795321/52533054-17a1d600-2d26-11e9-95b9-daa1a181db1b.png)

Please can I ask for more detail on your set up:
1) Is there significant difference between the code of my long running client and yours? Are you able to share your client code?
2) Are you running the client on a virtual machine, within a docker container or something else?
3) When you say it works after restarting the service, does this mean stopping and starting the process, rebooting the OS, restarting the docker container, or something else?
4) Is the client running on Linux, Windows or something else?
5) What is your KDC? Is this MIT KRB5KDC, Windows AD, or something else?

Thanks.

**Comment by jcmturner** [comment]
The issue may be in this line here and the logic used when a kvno of zero is used as an argument to this function:
https://github.com/jcmturner/gokrb5/blob/50a61c6f2226f37d6d94824c20942f1c7e06a2e3/client/client.go#L118

Can you give me the output of the following performed agains the keytab you are using?
```
ktlist -e -t -k <path to keytab file>
```

**Comment by sjokoladefoged** [comment]
@jcmturner sorry for the long wait, Sadly I don't have any details anymore as my last day there was 18th of February and another solution was found.
I don't see any major differences between your long running client and what was done back then - except that it was based on your http example.
