### ISSUE TITLE
SPNEGO with Active Directory (MechType is worng)

### ISSUE THREAD

**Issue by asaf** [jcmturner/gokrb5#22]
Hey,

First of all, thanks for this library, no more native dependencies in our stack :-)

We could successfully use it with ApacheDS but fail with AD,

First, we created a Keytab using the following command:
`ktpass -princ HTTP/myvm.mydomain.corp@MYDOMAIN.CORP -mapuser ad_sso_user -crypto AES-128-SHA1 -ptype KRB5_NT_PRINCIPAL -pass passw0rd -out c:\temp\my.ketab`

(etype for this AES-128-SHA1 is 0x11)

With AD, the 2nd HTTP roundtrip has the token header but fails on [this line](https://github.com/jcmturner/gokrb5/blob/master/service/http.go#L54)

Seems like gokrb5 expects `1.2.840.113554.1.2.2` while we receive from KDC `1.2.840.48018.1.2.2`, seems like this OID is a [krb5 with legacy bit](https://msdn.microsoft.com/en-us/library/ms995330.aspx).

No idea what causing AD to use this OID instead of the expected krb5 OID (any clue?)

Trying to comment out this condition we failed on:

`Could not get key from kteytab: Matching key not found in keytab. Looking for [HTTP myvm.mydomain.corp] realm: MYDOMAIN.CORP kvno: 3 etype: 23`

Not sure why ticket contains `etype: 23` while keytab was generated with etype: 17,

So we tried to generate a keytab with `RC4-HMAC-NT` etype, which is 23, we fail on [this line](https://github.com/jcmturner/gokrb5/blob/master/service/http.go#L79) with:

```
Unknown or unsupported checksum type: 4294967158
```
Seems like we fail [on pac type check](https://github.com/jcmturner/gokrb5/blob/master/pac/pac_type.go#L194)

It seems like `pac.ServerChecksum.SignatureType` value is `4294967158` while pac_type.go and crypto expects checksum types that corresponds to etypes, 

Any clue how to proceed from here ?

Thanks,

Asaf.

**Comment by asaf** [comment]
Alright, I've done some progress,
It seems like `RC4-HMAC-NT` is not supported, flagging the account with "AES 128 bit encryption" support started to make things appear differently,

It fails on a [nil reference when trying to set this line](https://github.com/jcmturner/gokrb5/blob/master/credentials/credentials.go#L198)

Here's a small stack trace using the latest version:

```
myproj/vendor/gopkg.in/jcmturner/gokrb5.v1/credentials.(*Credentials).AddAuthzAttribute(...)
myproj/vendor/gopkg.in/jcmturner/gokrb5.v1/credentials/credentials.go:198
myproj/vendor/gopkg.in/jcmturner/gokrb5.v1/credentials.(*Credentials).SetADCredentials(0xc4201d5578, 0xc420446e18, 0x4, 0xc420446e30, 0xd, 0x18b9, 0x201, 0x1b3042f4, 0xed16447d3, 0x0, ...)
myproj/vendor/gopkg.in/jcmturner/gokrb5.v1/credentials/credentials.go:119 +0x147
myproj/vendor/gopkg.in/jcmturner/gokrb5.v1/service.ValidateAPREQ(0x5, 0xe, 0xc4202785a8, 0x4, 0x4f6, 0x20, 0x5, 0xc420207940, 0xa, 0x3, ...)
...
```

**Comment by asaf** [comment]
@jcmturner a small PR to initialize credential's groupMembership before assigning values to it fixes the issue,

btw, if `gssapi.MechTypeOIDMSLegacyKRB5` is a legal value for SPNEGO auth then it would make sense to add it as an option to [this if statement](https://github.com/jcmturner/gokrb5/blob/master/service/http.go#L54), seems like things work just fine when removing this line, I'm really not sure what causing some of of the AD DCs to use this OID (probably some old ADs)

Thanks.

**Comment by jcmturner** [comment]
You've raised a few things here. Let me try and address each one in turn...

### [SPNEGO OID of MechToken is not of type KRB5](SPNEGO OID of MechToken is not of type KRB5)
I will need to have a look into this. I think the OID is set by the client and not the KDC. What is the client you are using?
It may be that it just needs to accept this OID too.

### EncType 23
Your AD KDC seems to be returning a ticket using enctype 23.
I don't know too much on the details of the Microsoft implementation but this is from the [MIT KDC documentation](https://web.mit.edu/kerberos/krb5-latest/doc/admin/enctypes.html):

> The KDC will only use the first key in the list of long-term keys for encrypting the service ticket, but the additional long-term keys indicate the other enctypes that the service supports.

So it seems that the ticket returned from the KDC does not have to use the same enctype as the messages between your client and the KDC that contains the ticket. Therefore you need to have your service's keytab contain the service credential using enctype 23 also.

Type 23 (RC4-HMAC) was recently implemented so you may need to "go get" an up to date version of gokrb5.

### Nil reference for groupMembership in Credential
The pull request you've submitted seems to make sense. Thanks!

**Comment by jcmturner** [comment]
Looks like it should accept the legacy OID...

https://msdn.microsoft.com/en-us/library/ms995330.aspx
> Server decodes the NegTokenInit, extracts the supported MechTypes (the one at the front of the MechTypeList should be either Kerberos Legacy or Kerberos V5), ensures it is one of the expected ones, and then extracts the MechToken and authenticates using gss_accept_security_context.

**Comment by asaf** [comment]
"Looks like it should accept the legacy OID..."
So consider adding this MechType to the http service (I tested, it works fine)

"What is the client you are using?"
I don't think this is client related, I tried logging in using Linux/Windows and used different kind of http clients (chrome / IE), I always got MechType 23, once I flagged the account in AD with "AES 128/256 support" I started to get MechType 17 as I expected, so seems like AD defines the MechType based on the account associated with the SPN.
