### ISSUE TITLE
Reading full request body before returning with 401

### ISSUE THREAD

**Issue by szilardhuber** [jcmturner/gokrb5#220]
I created a SPNEGO authentication http server using gokrb5. I run it on Windows behind an nginx proxy.  

What I experience is that when uploading bigger requests (like file upload), sometimes I get 502 Bad Gateway on the client from the nginx proxy and in the nginx error logs I see the following error:   

```WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream```

After some debugging it seems that the issue is that the `SPNEGOKRB5Authenticate` method writes the response without reading the request body. (I'm not sure if it is really required to read the whole message body, I found the following sentence in `RFC 7230 (chapter 6.3 Persistence)` that might relate to this question: 
> A server MUST read
   the entire request message body or close the connection after sending
   its response, since otherwise the remaining data on a persistent
   connection would be misinterpreted as the next request.

If I patch the module the following way everything works like charm in my test scenario:

```
		if len(s) != 2 || s[0] != HTTPHeaderAuthResponseValueKey {
			ioutil.ReadAll(r.Body)
			w.Header().Set(HTTPHeaderAuthResponse, HTTPHeaderAuthResponseValueKey)
			w.WriteHeader(401)
			w.Write([]byte(UnauthorizedMsg))
			return
		}
```

Do you think this change would make any sense?

**Comment by jcmturner** [comment]
I'm not sure this is the right way to address this. It does not seem safe to me to read all the posted body from an unauthenticated client. For example a denial of service could be performed by sending a very large amount of data. I have looked at other Go HTTP authentication solutions and they do not do this either.

In the error message you see I interpret the "remote host" as the client and "upstream" as your Go http server. Therefore it seems that the client uploading is forcibly closing the connection.

With regards to the RFC it specifies that the connection must be closed after sending the 401 response. The way the code is implemented means we are already doing this.

I have some updated tests to cover an upload. These seem to work with no issues.

**Comment by szilardhuber** [comment]
Thank you for the detailed and very friendly answer @jcmturner. :)  I think you are right with the DoS danger of my changes.

I guess this might be a Windows+Nginx issue in my case then. Thanks again, I'm closing the issue.
