### ISSUE TITLE
ValidateAPREQ does not check ServiceName

### ISSUE THREAD

**Issue by Folcky** [jcmturner/gokrb5#229]
e.g. for example if you have two services with the same keys in keytabs, you can authenticate on both of them.

**Comment by jcmturner** [comment]
Checking the RFC (https://tools.ietf.org/html/rfc4120#section-3.2.3) the only items I can see that relate to this validation are:

> Because it is possible for the server to be registered in multiple
   realms, with different keys in each, the srealm field in the
   unencrypted portion of the ticket in the KRB_AP_REQ is used to
   specify which secret key the server should use to decrypt that
   ticket.The KRB_AP_ERR_NOKEY error code is returned if the server
   doesn't have the proper key to decipher the ticket.
   The ticket is decrypted using the version of the server's key
   specified by the ticket.


> If multiple servers (for example, different services on one machine,
   or a single service implemented on multiple machines) share a service
   principal (a practice that we do not recommend in general, but that
   we acknowledge will be used in some cases)...

Neither of these quotes say that the ServiceName in the ticket should be checked against anything. Only that the value should be used to lookup the key from the keytab (something I will check on). As you can see the recommended practice is not to use the same service principal for multiple services.

If you can share any more detail it would help me make sure we are talking about the same thing here.

Thanks.
