### ISSUE TITLE
How decode token from AD

### ISSUE THREAD

**Issue by Shamil-R** [jcmturner/gokrb5#230]
I made my own server, and place it in domain.
Now, i want give clients to auth with Windows account.
So, i builded thing like on this [picture](https://msdn.microsoft.com/en-us/library/ms995329.http-sso-1-fig03(l=en-us).gif)
My server get token in header Authenticate `Negotiate YII...`, and i stuck in step 5
How decode and check this token?

P.S. keytab from KDC i have.

**Comment by jcmturner** [comment]
Perhaps this example will help:
https://github.com/jcmturner/gokrb5/blob/12682928eb798abc1dd97ab419ab82c758e01e8a/examples/example-AD.go#L66-L75
