### ISSUE TITLE
Keytab loading from file broken since refactor

### ISSUE THREAD

**Issue by bodgit** [jcmturner/gokrb5#258]
The following code:
```golang
package main

import "gopkg.in/jcmturner/gokrb5.v7/keytab"

func main() {
        ktFromFile, err := keytab.Load("/tmp/my.keytab")
        if err != nil {
                panic(err)
        }
}
```
Now triggers a SIGSEGV:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4aff08]

goroutine 1 [running]:
gopkg.in/jcmturner/gokrb5.v7/keytab.(*Keytab).Unmarshal(0x0, 0xc00009a000, 0x59, 0x259, 0x259, 0x0)
        /home/matt/work/pkg/mod/gopkg.in/jcmturner/gokrb5.v7@v7.0.0/keytab/keytab.go:149 +0x88
gopkg.in/jcmturner/gokrb5.v7/keytab.Load(0x4ecab6, 0x14, 0xc000068058, 0x0, 0xc000036768)
        /home/matt/work/pkg/mod/gopkg.in/jcmturner/gokrb5.v7@v7.0.0/keytab/keytab.go:114 +0x90
main.main()
        /home/matt/test.go:10 +0x3a
```
I think it's since `keytab.Load()` was changed to return a `*keytab.Keytab` instead of `keytab.Keytab` [here](https://github.com/jcmturner/gokrb5/blob/c281e5886158a1d42bd3e73654c7403ae0761e42/keytab/keytab.go#L109), as it now defaults to a `nil` pointer rather than an empty struct, the bug is triggered when you assign to `kt.version` [here](https://github.com/jcmturner/gokrb5/blob/c281e5886158a1d42bd3e73654c7403ae0761e42/keytab/keytab.go#L149).

**Comment by bodgit** [comment]
Updating `keytab.Load()` to include the following before calling `kt.Unmarshal(b)` fixes it for me:
```golang
kt = &Keytab{}
```

**Comment by jcmturner** [comment]
@bodgit thanks for pointing this out. Will get on it right away.
