### ISSUE TITLE
Keyring Support

### ISSUE THREAD

**Issue by ncsurfus** [jcmturner/gokrb5#268]
Does this project support Keyrings as noted here?
https://web.mit.edu/kerberos/krb5-latest/doc/basic/ccache_def.html

> KEYRING:session:name - session keyring
KEYRING:user:name - user keyring
KEYRING:persistent:uidnumber - persistent per-UID collection. Unlike the user keyring, this collection survives after the user logs out, until the cache credentials expire. This type of ccache requires support from the kernel; otherwise, it will fall back to the user keyring.

**Comment by jcmturner** [comment]
gokrb5 does not interact with the keyring but I did find this library: https://github.com/zalando/go-keyring

Perhaps using this to store the password or keytab would give you what you need?

**Comment by ncsurfus** [comment]
It looks like the MIT Kerberos implemention relies on a Linux kernel keyring while the go-keyring library uses the gnome keyring. They appear to be different things. I’d like to provide an http client that supports Kerberos / Negotiate, but I’d rather not have some users change their krb5.conf file from the default based keytab+keyring to a keytab+file. Although retrieving the keytab from the keyring may simply be out of the scope for this project.

**Comment by ncsurfus** [comment]
I haven’t taken a deep dive, but this may be what I’m looking for.
https://github.com/jsipprell/keyctl

**Comment by jcmturner** [comment]
The library you've found seems to work well. You should be able to load the keytab bytes from the keychain using it and then create the keytab type with:
```go
// kb is a []byte loaded from the keychain using github.com/jsipprell/keyctl
kt := new keytab.Keytab
err := kt.Unmarshal(kb)
```

It's not in the scope of this library to interact with the keychain. Please let us know how you get on and share any example code...
