### ISSUE TITLE
"SID revision value read as 4 when it must be 1"

### ISSUE THREAD

**Issue by asaf** [jcmturner/gokrb5#27]
Hey,

I have a SPNEGO flow that worked fine for some user but suddenly I started to get this error:

`SID revision value read as 4 when it must be 1`

In parallel I tried with other user and it worked fine, but i'm not sure what causing the SID.revision to be 4 instead of 1 for a specific user (tried purging klist ticket, etc... nothing works)
Any clue what could have caused this ?
Microsoft papers don't say much except that revision value in SID should be 0x1 but it is not and I'm a bit clueless,

Thanks,

Asaf.

**Comment by jcmturner** [comment]
This error message comes from [this code](https://github.com/jcmturner/gokrb5/blob/master/mstypes/sid.go#L27-L29) which checks the revision is 1. According to the [Microsoft documentation](https://msdn.microsoft.com/en-us/library/cc230364.aspx) this MUST be the case. So I think the code is right according to the documentation. However there is little information as to what this value represents. I'll have a google  around as I'd want to know more about this field before changing this logic as the documentation available is pretty explicit.

**Comment by jcmturner** [comment]
I have found this quote "As of Windows 7 and Server 2008 R2 the SID specification is still in the first revision." I don't know if the number has changed for domain controllers newer that 2008 R2. Still hunting.

If you comment out the code lines that perform this check does it work for this user? I'm wondering if for some reason is the bit stream is shifted by two bits making this number 4 rather than 1. If the parsing of the rest of this users details works this would indicate this is not the case.

**Comment by asaf** [comment]
@jcmturner yea i know, I tried to find more info about it but can't,
Well, that's the case in real AD environments (a bit complicated one with some trusts between domains, we login to one domain and access a server from another domain)

I tried commenting this if condition and then failed on  [this line](https://github.com/jcmturner/gokrb5/blob/22b8cb19ed1378a4087995ab6a4adcf7e7f27b91/pac/kerb_validation_info.go#L205) expecting value '1' but got something else (very long number)

Well, since we'r totally stuck, I thought maybe we could skip PAC, Some usages (such as ours) require only to validate SPNEGO tokens and use the principal for authentication,

What do you think about making it possible to [skip pac](https://github.com/jcmturner/gokrb5/blob/master/messages/Ticket.go#L209) by some hint somehow ?

Thanks.

**Comment by asaf** [comment]
@jcmturner I think it's 2016 here but the odd thing is that it worked just fine for the (same user!) two days ago and then stopped (nobody changed anything, it was a weekend here)

**Comment by jcmturner** [comment]
Has this user been added or removed from any groups? Is this user a member of any groups?

**Comment by asaf** [comment]
@jcmturner it is member of many groups but these groups have not changed during the last 2 days between the time kerberos worked -> stopped working.

**Comment by jcmturner** [comment]
Can you give me some more info...
* Is the user in the same domain as the KDC it is authenticating to?
* Is the user authenticating to a service in the same or different domain?
* Is the user in groups within its own domain?
* Is the user in groups from other domains?

**Comment by asaf** [comment]
> Is the user in the same domain as the KDC it is authenticating to?
No, this is the flow:
- the user (e.g. "jcmturner") logs into a windows workstation of domain PROD.COM
- the user then open a browser to a server that has SPN configured in domain TEST.COM (e.g., "http/app1@TEST.COM", the SPN is attached to a another user in the TEST.COM domain (e.g., "krb5_sso")
- the SPNEGO token received by the server that is built with _gokrb5_ has a token for principal _jcmturner@PROD_ for SPN _http/app1@TEST.COM_

> Is the user authenticating to a service in the same or different domain?
Hope I answered in the first question
> Is the user in groups within its own domain?
user is part of domain PROD.COM and has groups in PROD.COM
> Is the user in groups from other domains?
I just checked, lately this user became a member of groups *within domain TEST.COM as well*.

**Comment by asaf** [comment]
@jcmturner
Ok I found the cause of this problem, it happens when the user is a member of groups associated to another domain.

**Comment by jcmturner** [comment]
OK thanks, it may take me a while to create a set up to re-create this.

**Comment by asaf** [comment]
Yes it will,

Let me know if I can help further.

**Comment by jcmturner** [comment]
@asaf 
I think I finally have an environment to try and recreate your problem so I can investigate a fix...

**Comment by asaf** [comment]
@jcmturner awesome, it seem to happen on every cross domain references so I think you'll be able to easily reproduce.

**Comment by jcmturner** [comment]
@asaf 
I'm having trouble re-creating your issue. I created the following set up:

- User domain: USER.GOKRB5
- Resource domain: RES.GOKRB5
- Authenticated as user: testuser1@USER.GOKRB5
- Requested service ticket to: HTTP/host.res.gokrb5 which is registered as an SPN against a user in the RES.GOKRB5 domain.
- Parse the service ticket PAC content

This seems to parse correctly.
I captured the PAC bytes and wrote this test: https://github.com/jcmturner/gokrb5/blob/issue-27/pac/kerb_validation_info_test.go#L204
It passes OK.
The updates are on branch: issue-27 

I found some other issues along the way but these seem to have been client side issues rather than the service side which is what you are having trouble with.

Does the set up I have described equate to your environment? Do you have other trusts involved?

**Comment by asaf** [comment]
@jcmturner Not that i'm aware of, this is exactly my flow, maybe it has something to do with active directory domain level compatibility ? if you can guide me through I can try to capture the PAC bytes if it helps.

**Comment by jcmturner** [comment]
The PAC bytes would help. Not sure if you'd be ok sending to me though. You can use wireshark to get this by running on the client filtering for traffic on port 88. Right click in the packet details pane and go to Protocol Preferences > Kerberos keytab file... select the keytab of the service.
Now find the tgs-rep and expand as outlined below.
```
tgs-rep
    ticket
        enc-part
            cipher: b2975389c1f071ca9ab383f0394c95e0e08bd328028e7f31...
                encTicketPart
                    authorization-data: 1 item
                        AuthorizationData item
                            ad-data: 308203223082031ea00402020080a1820314048203100500...
                                AuthorizationData item
                                    ad-data: 050000000000000001000000100200005800000000000000...
                                        Type: Logon Info (1)
                                            PAC_LOGON_INFO: 01100800cccccccc000200000000000000000200194f0167...
```
Right click on the PAC_LOGON_INFO and copy the value. These are the decrypted bytes of part of the PAC.
You could then run these through a test like the one at: TestKerbValidationInfo_Unmarshal_DomainTrust in pac/kerb_validation_info_test.go
Obviously you'd have to put in your specific details which you can get from the wireshark output.

**Comment by asaf** [comment]
@jcmturner Alright then, it will take me some time to whitelist Wireshark,
I'll post the conclusions when I have them

Thanks.

**Comment by jcmturner** [comment]
@asaf did you manage to investigate this any further?

**Comment by asaf** [comment]
@jcmturner a bit stuck with this as it happens in finance companies (tough to whitelist a sniffer :/)

**Comment by jcmturner** [comment]
@asaf are you able to run tcpdump on the server running the service?

You could...
```tcpdump port 88 -s 0 -w /tmp/pacissue.cap```

Then copy this capture to a workstation that you can have wireshark on to extract as above....?

**Comment by asaf** [comment]
@jcmturner 
Hey there, I want to proceed with this but I don't see any packets captured on port 88,

> you able to run tcpdump on the server running the service?
Are you sure it needs to run on the service ? I thought that the server running the service doesn't perform any network activity rather try to decrypt the token locally


Thanks.

**Comment by jcmturner** [comment]
Does the machine have more than one interface? Are you capturing on the right interface? Also I'm assuming your KDC is listenning on port 88 (the default for kerberos).

**Comment by asaf** [comment]
@jcmturner i put the right interface, but yet again, since when the service needs access to the KDC?  IIRC spnego auth flow doesn't have any interaction between service -> KDC

**Comment by jcmturner** [comment]
Ahhh yes sorry you are right you won't see this on the service. This capture needs to be run on the client machine. You could do this with tcpdump on a linux machine. You will need to do the following while running the capture:

* A correct /etc/krb5.conf file for your kerberos environment
* Run: kinit <username@realm> for the use that 
* Then run: kvno <SPN, eg HTTP/myhost.domain.com>

**Comment by asaf** [comment]
@jcmturner Okay that makes more sense :)
Well, it's a windows machine so i guess i'm stuck, I'll try to get some linux machine connected to the AD domain in order to proceed.

**Comment by jcmturner** [comment]
All you need is the right /etc/krb5.conf file on the Linux machine. There is nothing more to it than that to "connect it to the domain". You don't need anything like compute objects in the AD for it. You are just using it as a client.

**Comment by asaf** [comment]
@jcmturner done,

The kvno just prints something like:

_HTTP/myserver.mydomain.corp@MYDOMAIN.CORP: kvno = 6

**Comment by jcmturner** [comment]
Did you get the tcpdump while doing the kvno command?

**Comment by asaf** [comment]
@jcmturner yea ! do you need the TGS-REP part ?
I can also send you the whole file (privately if possible) if you give me some communication channel to do so (gtalk/skype/etc)

**Comment by asaf** [comment]
@jcmturner what are we going to do about this one? I'm willing to privately send you the SPNEGO ticket in base64 for further debugging if you are up to it, otherwise lets close this -- your call.

**Comment by jcmturner** [comment]
@asaf I have done some refactoring work of the PAC parsing that is currently in the master branch (not in a release yet). Can you try with this code to see if you get the same issue? Thanks.

**Comment by jcmturner** [comment]
I have made release 5.3.0 that I'd be interested if you can recreate this issue with.

**Comment by asaf** [comment]
@jcmturner same thing

**Comment by jcmturner** [comment]
OK thanks. I have been working on a full implementation of decoding NDR byte streams (https://github.com/jcmturner/rpc/ndr) which is what the PAC is encoded in. I'll be looking to covert gokrb5 to use this soon. I think I have a much more solid implementation of NDR decoding.

I'll let you know when I have something for you to try and I'm hopeful it will resolve this.

**Comment by asaf** [comment]
awesome, keep the good work 👍

**Comment by jcmturner** [comment]
I've released v6 of gokrb5 that uses a new NDR decoder. Can you try this and see if it resolves this issue? Thanks.

**Comment by jcmturner** [comment]
@asaf are you still seeing this issue with v6?

**Comment by asaf** [comment]
@jcmturner closing for now, will re-open if needed, thanks!
