### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by cloudsystema** [jcmturner/gokrb5#276]
Hi, I am getting below error when running against http sites which are working well with Kerberos via Chrome or Safari. My test client is same as httpClient under examples.
any help appreciated.

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0x71bbc6]

goroutine 5 [running]:
testing.tRunner.func1(0xc0000d4100)
        C:/Go/src/testing/testing.go:792 +0x38e
panic(0x78f6c0, 0xac64d0)
        C:/Go/src/runtime/panic.go:513 +0x1c7
gopkg.in/jcmturner/gokrb5.v7/client.(*Client).Key(0xc00005d4d0, 0x8671c0, 0xaef230, 0x0, 0x0, 0xc00024a240, 0x0, 0x1, 0xc000456370, 0x1)
        C:/projects/krb/src/gopkg.in/jcmturner/gokrb5.v7/client/client.go:120 +0x86
gopkg.in/jcmturner/gokrb5.v7/client.setPAData(0xc00005d4d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/projects/krb/src/gopkg.in/jcmturner/gokrb5.v7/client/ASExchange.go:94 +0xe2
gopkg.in/jcmturner/gokrb5.v7/client.(*Client).Login(0xc00005d4d0, 0xc00024a1a0, 0xc00024a1c0)
        C:/projects/krb/src/gopkg.in/jcmturner/gokrb5.v7/client/client.go:183 +0x177
gopkg.in/jcmturner/gokrb5.v7/spnego.(*SPNEGO).AcquireCred(0xc00024a1a0, 0x801cef, 0x2b)
        C:/projects/krb/src/gopkg.in/jcmturner/gokrb5.v7/spnego/spnego.go:47 +0x36
gopkg.in/jcmturner/gokrb5.v7/spnego.SetSPNEGOHeader(0xc00005d4d0, 0xc000112000, 0x801cef, 0x2b, 0x0, 0x7f4010)
        C:projects/krb/src/gopkg.in/jcmturner/gokrb5.v7/spnego/http.go:153 +0x13a
gopkg.in/jcmturner/gokrb5.v7/spnego.(*Client).Do(0xc00045a9c0, 0xc000112000, 0x0, 0x0, 0x1)
        C:/projects/krb/src/gopkg.in/jcmturner/gokrb5.v7/spnego/http.go:87 +0x2a7
gopkg.in/jcmturner/gokrb5.v7/spnego.(*Client).Do(0xc00045a9c0, 0xc0000d4300, 0x801cef, 0x2b, 0xc00045a9c0)
        C:/projects/krb/src/gopkg.in/jcmturner/gokrb5.v7/spnego/http.go:81 +0x196
krb.login(0x7f1e8a, 0x5, 0x12, 0xc0000dff58, 0x1, 0x1)
        C:/projects/krb/src/krb/login.go:70 +0x4d9
krb.TestLogin(0xc0000d4100)
        C:/projects/krb/src/krb/login_test.go:27 +0x147
testing.tRunner(0xc0000d4100, 0x80d4f0)
        C:/Go/src/testing/testing.go:827 +0xc6
created by testing.(*T).Run
        C:/Go/src/testing/testing.go:878 +0x35a

**Comment by srinathgs** [comment]
I have observed this as well. work around is by using a client on which `Login` method is not called.

**Comment by jcmturner** [comment]
I think the issue here is this line...

https://github.com/jcmturner/gokrb5/blob/50a61c6f2226f37d6d94824c20942f1c7e06a2e3/client/client.go#L120

The krberr can sometimes be nil but this is not being checked before this evaluation. Should be a quick fix.

**Comment by cloudsystema** [comment]
@jcmturner Thanks a lot for the quick response, looking froward to the fix. 
I am a newbie in Kerberos and may not know what I am doing :)
I am not sure if you can help me with my issues. Feel free to ignore though. 
Problem I am having is that on a Linux machine RH6 I am getting a correct response by using 
`curl --negotiate -u : <internal website address>` 

but getting this error when using gokrb5:
`ERROR: SPNEGO Client error:  could not initialize context: [Root cause: KDC_Error] KDC_Error: TGS Exchange Error: kerberos error response from KDC when requesting for <SPN name>: KRB Error: (7) KDC_ERR_S_PRINCIPAL_UNKNOWN Server not found in Kerberos database`

My code follows your httpclient example code.

I will keep debugging through your great code though, helps me to learn Kerberos
Thank you for taking time to put together Kerberos in Go!

**Comment by cloudsystema** [comment]
Sorry, never mind, I got it working...
I had a wrong name for SPN. 
I like this very much, works great!
Thank you.

**Comment by cloudsystema** [comment]
Thank you @jcmturner !
just fyi, this error null pointer is coming up for me when I explicitly use the client password and not when use the keytab file. I guess the fix makes sense then. I will try to reproduce with current code and new fix. 

One more question. When using keytab I realize that kvno number is important. And that I need to create a keytab file with correct kvno number. Is there a way to find the kvno matching number of the service before generating client keytab file?
Thank you!

**Comment by jcmturner** [comment]
Release 7.2.2 should have addressed this.

**Comment by duanlei123** [comment]
下载不下来
