### ISSUE TITLE
spnego.SPNEGOKRB5Authenticate overwrites the request context

### ISSUE THREAD

**Issue by shanmugh** [jcmturner/gokrb5#279]
In the code on HEAD `spnego.SPNEGOKRB5Authenticate` seems to be overwriting the request context, which can be painful if the context is already populated by the routers with URL params etc.

Relevant code: https://github.com/jcmturner/gokrb5/blob/master/spnego/http.go#L240-L243

**Comment by jcmturner** [comment]
Released in v7.2.3
