### ISSUE TITLE
Config reader doesn't support comments at the end of a line

### ISSUE THREAD

**Issue by jake-scott** [jcmturner/gokrb5#285]
The MIT profile parser (which includes parsing krb5.conf) supports comments on the end of lines (although admittedly this doesn't appear to be documented).  We use this as such :

```
  [realms]
     foo.bar = {
        kdc = 1.2.3.4   # kdc1.blah.com
        kdc = 2.3.4.5   # kdc2.blah.com
   }
```

The gokrb5 parser only supports the (documented) comment format -- ie. as the only thing on a line.

The fix is very simple - let me know if this is acceptable and I'll submit a PR.

**Comment by jake-scott** [comment]
After further investigation, MIT Kerberos actually only supports this on lines that specify hostnames like the kdc entries in the previous comment.  The code removes any space plus anything following, from the end of the hostname.

This diff seems to do the trick: 
```
diff --git a/config/krb5conf.go b/config/krb5conf.go
index dbc61c3..5170bf8 100644
--- a/config/krb5conf.go
+++ b/config/krb5conf.go
@@ -373,6 +373,12 @@ func (r *Realm) parseLines(name string, lines []string) (err error) {
                case "default_domain":
                        r.DefaultDomain = v
                case "kdc":
+                       // Only the first field is relevant -- MIT Kerberos ignores
+                       // the space and everything after it, after the hostname
+
+                       fields := strings.Fields(v)
+                       v = fields[0]
+
                        if !strings.Contains(v, ":") {
                                // No port number specified default to 88
                                if strings.HasSuffix(v, `*`) {
```

**Comment by jcmturner** [comment]
@jake-scott thanks for looking into this. It makes sense to me to have consistent behaviour with the MIT parser and there seems to be no downside to this solution. Would you be happy to submit a PR wit this improvement?
