### ISSUE TITLE
IPv6 addresses removed by KDC result in a TGSRep validation error

### ISSUE THREAD

**Issue by jake-scott** [jcmturner/gokrb5#286]
Our AD DCs strip IPv6 addresses that gokrb5 inserts the TGSReq messages, when it generates the TGSRep.  This causes a validation error.

I propose a fix that provides a new config option (IPv4Only) which prevents gokrb5 from populating  requests with IPv6 addresses.

I have this working in dev;  is this sounds acceptable I'll submit a PR.

**Comment by jcmturner** [comment]
I'd prefer to keep the configuration consistent to the MIT krb5.conf definition. Does it work for you if you set the NoAddresses to true?

**Comment by jcmturner** [comment]
@jake-scott does it work if you set NoAddresses to true?

**Comment by jcmturner** [comment]
@jake-scott I'm going to close this issue. Please re-open if you wish to continue discussing.
