### ISSUE TITLE
Allow access to a ticket's encrypted contents for the verifying party

### ISSUE THREAD

**Issue by donatello** [jcmturner/gokrb5#288]
A service verifying a service ticket should have access to the actual expiry time present in the encrypted portion of the ticket for application specific purposes.

This can be done by passing a pointer to APReq to `service.VerifyAPREQ`. This way the populated encrypted contents of the ticket are available when the call returns.

The specific application situation here, is that in Minio server, we want to give temporary credentials for users authenticated by Kerberos. We want to set the expiry time of the credentials as the expiry time of the service ticket.

This PR https://github.com/jcmturner/gokrb5/pull/284 implements this change.

**Comment by jcmturner** [comment]
@donatello thank you for raising this issue and clearly describing the use case. As this would be a breaking change to the API it will need to be a major version release. This may take some time to get released. In the meantime can I suggest doing the following with v7.

1. Verify the APREQ with ``service.VerifyAPREQ``
2. Decrypt the ticket within the APREQ:
```
err := apreq.Ticket.DecryptEncPart(kt, &apreq.Ticket.SName)
```

**Comment by jcmturner** [comment]
I have merged your PR into the branch that will become v8 (draft-v8).

**Comment by jcmturner** [comment]
addressed in newly release v8
