### ISSUE TITLE
Support client sessions for SPNEGO

### ISSUE THREAD

**Issue by jcmturner** [jcmturner/gokrb5#289]
Add functionality to the SPNEGOKRB5Authenticate http handler wrapper that will enable a session handler to be passed in. The aim is so that clients can establish sessions and not have to authenticate on every call.

**Comment by jcmturner** [comment]
Will likely require a major version iteration as the credentials struct will need to be serialisable. This requires a change to the goidentity.Identity interface.

**Comment by L11R** [comment]
@jcmturner thanks for the library. Are there any news on this enhancement? KDC is blocking me for too many ticket requests.

**Comment by L11R** [comment]
I made PR #338 with draft solution to understand better my issue.

**Comment by jcmturner** [comment]
added to v8
