### ISSUE TITLE
Encrypting error - trying to use aes256 instead of rc4-hmac

### ISSUE THREAD

**Issue by mikenolt** [jcmturner/gokrb5#294]
I am having the same issue as #186 - it is looking for etype 18 (aes256) but I am using 23 (rc4-hmac). I left a comment on that issue but you probably aren't going to see it since it is closed so am opening a new one.

Here is the full error:
`
Error on AS_REQ: [Root cause: Encrypting_Error] KRBMessage_Handling_Error: AS Exchange Error: failed setting AS_REQ PAData for pre-authentication required < Encrypting_Error: error getting key from credentials: matching key not found in keytab. Looking for [<redacted>] realm: <redacted> kvno: 0 etype: 18
`

Here is what is in the keytab:
Keytab name: FILE: redacted.keytab
KVNO Timestamp         Principal
   0 06/09/19 10:50:29 redacted@redacted (arcfour-hmac)

Here are the krb5.conf entries of interest:
`
default_tgs_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 arcfour-hmac-md5
default_tkt_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 arcfour-hmac-md5
permitted_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 arcfour-hmac-md5
`

I cannot modify the krb5.conf and if I try adding an entry for 18/aes256 (add_entry -password -p redacted@redacted -k 0 -e aes256-cts-hmac-sha1-96) to the keytab, I get an error that says...
kinit: Preauthentication failed while getting initial credentials
...and Kerberos doesn't work at all. In my setup, Kerberos only works if there is 1 entry in the keytab and it is the rc4-hmac.

Is there a way to force gokrb5 to use rc4-hmac instead of aes256 or another way to get things working?

Note that I am new to Kerberos so apologize if that is a silly question or I am missing something easy.

Thanks

**Comment by jcmturner** [comment]
Hi @mikenolt 

I see you have added the aes256 value to the keytab with a kvno of zero. I can understand why you have done this given the first error message but I don't think this will be the right value. The kvno is the version of the password for that user in the directory so every time the password is changed the kvno increments. Therefore it will not be zero. Can you try removing the kvno=0 entry and putting the aes256 entry in with a kvno of 1. When you run this again I think it may error again but it should tell you the correct value of kvno to use.

**Comment by mikenolt** [comment]
Thanks for the quick response @jcmturner!

I had tried using kvno 1 before and got another error so tried using 0 like in the error. I just added it with 1 (add_entry -password -p redacted@redacted -k 1 -e aes256-cts-hmac-sha1-96) and get the same error:
kinit: Preauthentication failure while getting initial credentials

And get this error when trying to run the program:
Error on AS_REQ: [Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (24) KDC_ERR_PREAUTH_FAILED Pre-authentication information was invalid

ktutil:  l -e
slot KVNO Principal
---- ---- ---------------------------------------------------------------------
   1    0           redacted@redacted (arcfour-hmac)
   2    1           redacted@redacted (aes256-cts-hmac-sha1-96)

**Comment by jcmturner** [comment]
Is your client time synced with ntp?

Are you able to get a wireshark trace during this?

**Comment by mikenolt** [comment]
Yes, the node is syncing with ntp but no, I cannot get a wireshark trace. Company policy won't allow that.

I might be able to ask someone on the networking side to look at it if I know what I'm looking for.

**Comment by jcmturner** [comment]
For reference the flow for pre-authentication is...

1) Client sends AS_REQ to kerberos server (KDC). This includes a definition of which enctypes the client can support (taken from the krb5.conf). In this case you are showing you support 18.
2) KDC responds with error stating pre-authentication is required and which enctype to use (selected from those the client can support). It is selecting 18 as it is the best available.
3) The client takes the current time and encrypts it using the user's password and the enctype specified (18 in this case). For this it needs a keytab entry that matches this enctype, so if it is not present in the keytab you get the first error message you posted.
4) The client repeats the AS_REQ which now also includes this encrypted time value
5) The KDC checks the encrypted time value matches what it would generate

I'm a little confused when you say you get this error:
```
Error on AS_REQ: [Root cause: Encrypting_Error] KRBMessage_Handling_Error: AS Exchange Error: failed setting AS_REQ PAData for pre-authentication required < Encrypting_Error: error getting key from credentials: matching key not found in keytab. Looking for [<redacted>] realm: <redacted> kvno: 0 etype: 18
```
but you also say ``In my setup, Kerberos only works if there is 1 entry in the keytab and it is the rc4-hmac.``

These two things seem to contradict. Can you clarify?

BTW I assume you have checked the password you are using for creating the keytab entries is correct? ;-)

**Comment by mikenolt** [comment]
Thanks for the details on the flow.

I am new to kerberos so sorry if some things I am saying don't make a lot of sense initially...

What I was trying to say is when I run the go program, I get the encrypting error. If I try adding anything to the keytab, kerberos will not work at all (gets the preauthentication failure.) Kerberos only works (I verify it is working or not by doing an -ls on HDFS) if rc4-hmac is the only entry in the keytab.

Does that make more sense?

And, yes, it is my password that I am using for creating keytab entries. I have run the command several times just to make sure I wasn't typing it incorrectly. :-)

**Comment by mikenolt** [comment]
And, maybe a rookie question but why would the client say it supports 18 when the only thing in the keytab is rc4-hmac? Is that because 18/aes256 is the first thing in the default enctypes strings in the krb5.conf file? Is there a way to tell the client to send rc4-hmac instead of aes256?

**Comment by mikenolt** [comment]
I am wondering if maybe I am doing something else wrong. I got (most of) the code below from [https://github.com/colinmarc/hdfs/issues/175](url)

Does it look okay to you? Seems right to me, just wanted to be sure.

`

    func getkrbClient() (*krbclient.Client, error) {
       configPath := os.Getenv("KRB5_CONFIG")
       if configPath == "" {
           configPath = "/etc/krb5.conf"
       }
       // Prints /etc/krb5.conf
       fmt.Println("Config path is:", configPath)

       cfg, err := config.Load(configPath)
       if err != nil {
           return nil, err
       }

       kt, err := keytab.Load("/home/<redacted>/.ssh/kerberos/<redacted>.keytab")
       if err != nil {
           fmt.Printf("Error - keytab load failed. %s", err.Error())
           return nil, err
       }
       fmt.Println("keytab loaded, contents are:", kt)

       client := krbclient.NewClientWithKeytab("<redacted>", "<redacted>", kt)
       fmt.Println("NewClientWithKeytab ok.")

       client.WithConfig(cfg)

       fmt.Println("Logging in...")
       // This is where it gets the error
       // Log in the client
       err = client.Login()
       if err != nil {
           fmt.Printf("Error on AS_REQ: %v\n", err)
           return nil, err
       }

       return &client, nil
    }
`

**Comment by jcmturner** [comment]
@mikenolt, you're not asking rookie questions.

I see from this code that you must be using an older version of gokrb5. Can you update to v7 as it will make things easier to investigate.
This will change these lines:
```
   client := krbclient.NewClientWithKeytab("<redacted>", "<redacted>", kt)
   fmt.Println("NewClientWithKeytab ok.")

   client.WithConfig(cfg)
```
which become just the following under v7
```
   client := krbclient.NewClientWithKeytab("<redacted>", "<redacted>", kt, cfg)
   fmt.Println("NewClientWithKeytab ok.")
```

Are you using Active Directory as you kerberos server?

If so then I would create the client with an additional option:
```
client := krbclient.NewClientWithKeytab("username", "REALM.COM", kt, cfg, client.DisablePAFXFAST(true))
```

**Comment by mikenolt** [comment]
The colinmarc hdfs client I am trying to use requires krb5.v5 (and rpc v.0) which is why I am using that version.

Just for trying to figure this out, I downloaded krb5.v7 and rpc.1. Still get the same error:

`Error on AS_REQ: [Root cause: Encrypting_Error] KRBMessage_Handling_Error: AS Exchange Error: failed setting AS_REQ PAData for pre-authentication required < Encrypting_Error: error getting key from credentials: matching key not found in keytab. Looking for [<redacted>] realm: <redacted> kvno: 0 etype: 18`

Here is the updated code:
`

    import (
        "os"
        "fmt"
        "gopkg.in/jcmturner/gokrb5.v7/config"
        krbclient "gopkg.in/jcmturner/gokrb5.v7/client"
        keytab "gopkg.in/jcmturner/gokrb5.v7/keytab"
    )

    func getkrbClient() (*krbclient.Client, error) {
        configPath := "/etc/krb5.conf"
        cfg, err := config.Load(configPath)
        if err != nil {
            return nil, err
        }

        kt, err := keytab.Load("/home/<redacted>/.ssh/kerberos/<redacted>.keytab")
        if err != nil {
            fmt.Printf("Error - keytab load failed. %s", err.Error())
            return nil, err
        }
        fmt.Println("keytab loaded, contents are:", kt)

        client := krbclient.NewClientWithKeytab("<redacted>", "<redacted>" kt, cfg, krbclient.DisablePAFXFAST(true))
        fmt.Println("NewClientWithKeytab ok.")

        fmt.Println("Logging in...")
        // This is where it gets the error
        // Log in the client
        err = client.Login()
        if err != nil {
            fmt.Printf("Error on AS_REQ: %v\n", err)
            return nil, err
        }

        return nil, nil
    }
`

**Comment by mikenolt** [comment]
By the way, I was able to (sort of) get things working with v5 by using the credentials cache file. I say sort of because I connect now (as far as I can tell) but hit another [issue](https://github.com/colinmarc/hdfs/issues/144) when trying to use the hdfs client.

I know this isn't the right way to do it, I just wanted to see for myself that it would actually work when we get things right.

Here is that code:
Note that I am not using Login() here. Can you confirm that is correct - I don't need to use Login() when using the cache since it's already logged in?

`

    func getkrbClient() (*krbclient.Client, error) {
        configPath := "/etc/krb5.conf"
        cfg, err := config.Load(configPath)
        if err != nil {
            return nil, err
        }

        ccache, err := credentials.LoadCCache("/tmp/{cacheFile}")
        if err != nil {
            fmt.Printf("Error - ccache load failed. %s", err.Error())
            return nil, err
        }

        // Print some info from the cache
        fmt.Println("ccache is")
        fmt.Println(ccache.GetClientPrincipalName())
        fmt.Println(ccache.GetClientRealm())
        fmt.Println(ccache.GetClientCredentials())

        client, err := krbclient.NewClientFromCCache(ccache)
        if err != nil {
            fmt.Printf("Error - ccache getting new client from cache. %s", err.Error())
            return nil, err
        }

        client.WithConfig(cfg)

        return &client, nil
    }
`

**Comment by mikenolt** [comment]
FYI, I used the workaround (modifying kerberos.go and namenode.go) provided in the link for the issue above and verified that I am in fact connecting to HDFS (without calling Login()) and can list the directory contents.

Just need to get it working without using the ccache file.

**Comment by jcmturner** [comment]
> The colinmarc hdfs client I am trying to use requires krb5.v5 (and rpc v.0) which is why I am using that version.
> 
> Just for trying to figure this out, I downloaded krb5.v7 and rpc.1. Still get the same error:
> 
> `Error on AS_REQ: [Root cause: Encrypting_Error] KRBMessage_Handling_Error: AS Exchange Error: failed setting AS_REQ PAData for pre-authentication required < Encrypting_Error: error getting key from credentials: matching key not found in keytab. Looking for [<redacted>] realm: <redacted> kvno: 0 etype: 18`
> 
> Here is the updated code:
> `
> 
> ```
> import (
>     "os"
>     "fmt"
>     "gopkg.in/jcmturner/gokrb5.v7/config"
>     krbclient "gopkg.in/jcmturner/gokrb5.v7/client"
>     keytab "gopkg.in/jcmturner/gokrb5.v7/keytab"
> )
> 
> func getkrbClient() (*krbclient.Client, error) {
>     configPath := "/etc/krb5.conf"
>     cfg, err := config.Load(configPath)
>     if err != nil {
>         return nil, err
>     }
> 
>     kt, err := keytab.Load("/home/<redacted>/.ssh/kerberos/<redacted>.keytab")
>     if err != nil {
>         fmt.Printf("Error - keytab load failed. %s", err.Error())
>         return nil, err
>     }
>     fmt.Println("keytab loaded, contents are:", kt)
> 
>     client := krbclient.NewClientWithKeytab("<redacted>", "<redacted>" kt, cfg, krbclient.DisablePAFXFAST(true))
>     fmt.Println("NewClientWithKeytab ok.")
> 
>     fmt.Println("Logging in...")
>     // This is where it gets the error
>     // Log in the client
>     err = client.Login()
>     if err != nil {
>         fmt.Printf("Error on AS_REQ: %v\n", err)
>         return nil, err
>     }
> 
>     return nil, nil
> }
> ```
> 
> `

When you did this did you add the entry to the keytab using the aes256 enctype and try it?

**Comment by mikenolt** [comment]
No. As previously stated, Kerberos doesn't work at all (gets a preauthentication error) if there is anything other than rc4-hmac in the keytab. I need a way to make the krb5 client use rc4-hmac instead of aes256.

**Comment by jcmturner** [comment]
To do this you need to take a copy of the krb5.conf, edit it to remove the references to ``aes256-cts-hmac-sha1-96`` and ``aes128-cts-hmac-sha1-96`` and then use this where you load the config...

```
cfg, err := config.Load(configPath)
    if err != nil {
        return nil, err
    }
```

**Comment by mikenolt** [comment]
Okay, tried that, still doesn't work.

Copied the krb5.conf to local directory and changed these lines:
  default_tgs_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 arcfour-hmac-md5
  default_tkt_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 arcfour-hmac-md5
  permitted_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 arcfour-hmac-md5

To:
  default_tgs_enctypes = rc4-hmac
  default_tkt_enctypes = rc4-hmac
  permitted_enctypes = rc4-hmac

Also tried arcfour-hmac and arcfour-hmac-md5

Get this error no matter what was used above:
`
Error on AS_REQ: [Root cause: Encrypting_Error] KRBMessage_Handling_Error: AS Exchange Error: failed setting AS_REQ PAData for pre-authentication required < Encrypting_Error: error getting key from credentials: matching key not found in keytab. Looking for [<redacted - matches what is printed out in the keytab contents below>] realm: <redacted - matches what is printed out in the keytab contents below> kvno: 0 etype: 23
`

Here is what it shows as the contents of the the keytab:
`
keytab loaded, contents are: &{2 [{{1 <redacted - matches the realm in the error above> [<redacted - matches the user in the error above>] 1} 2019-06-09 10:50:29 -0400 EDT 0 {23 [re dac ted red ac ted red act ed r dac te dr eda cte dr]} 0}]}
`
  
And the ktutil output:
ktutil:  l -e
slot KVNO Principal
   1    0           \<redacted\>@\<redacted\> (arcfour-hmac)

**Comment by dantangfan** [comment]
hi @jcmturner , I wonder if it's possible to add some weak crypto, such as des-cbc-crc/des3-hmac-sha1？For our KDC was build at early 2012, and doesn't support all the 5 cryptos listed on README page~ thanks

**Comment by mikenolt** [comment]
@jcmturner Any thoughts on the above? Is there anything else I can do/try to get things working?

**Comment by jcmturner** [comment]
Do you have preferred_preauth_types defined in your krb5.conf? Either way can you try when this is configured to be:

```
preferred_preauth_types  = 23
```

**Comment by jcmturner** [comment]
Let me know if the ``preferred_preauth_types`` configuration above works. If not please re-open this issue.
