### ISSUE TITLE
is client.Client thread safe?

### ISSUE THREAD

**Issue by vigith** [jcmturner/gokrb5#30]
``` golang
  conf, err := config.Load("/etc/krb5.conf")
  cc, err := credentials.LoadCCache("/tmp/krb5cc_20115788")
  fmt.Println(cc.GetClientPrincipalName())
  cl, err := client.NewClientFromCCache(cc)
  if err != nil {
    panic(err)
  }
  cl.WithConfig(conf)
```

Can i pass `cl` to multiple go routines? The go routines will be doing something like

```golang
  r, _ := http.NewRequest("GET", "http://kerberized.end.point", nil)
  cl.SetSPNEGOHeader(r, "")
  httpResp, err := http.DefaultClient.Do(r)
  defer httpResp.Body.Close()
```

"`GetServiceTicket` makes a request to get a service ticket for the SPN specified and The ticket will be added to the client's ticket cache", will there be a race condition here? or in any other place.

**Comment by jcmturner** [comment]
Hi, I think there could be some problems in the caching of the tickets as multiple threads would be writing to the maps of the client cache at the same time. Therefore I would recommend that you create a new client instance per thread at the moment. Not an optimised approach but it should work. It will take some work to make the client thread safe.

**Comment by vigith** [comment]
How about i do this? Persist `tkt` and `skey` and pass it to my go routines. Since `GetServiceTicket` is called outside of the go routines (1 time call during initialization) will i run into race conditions?

```golang
  var spn = "HTTP/" + "nosuch.example.com"
  var tkt messages.Ticket
  var skey types.EncryptionKey
  tkt, skey, err = cl.GetServiceTicket(spn)
```

Now my go routines will be doing something like 

```golang
  r, _ := http.NewRequest("GET", url, nil)

  // h is my shared struct which will have *client.Client,  messages.Ticket, types.EncryptionKey
  // h is initialized before starting the go routines.
  err = client.SetSPNEGOHeader(*h.krb5cl.Credentials, h.tkt, h.skey, r)
  if err != nil {
    // ...
  }
```
