### ISSUE TITLE
Move test/testenv to its own repository?

### ISSUE THREAD

**Issue by miekg** [jcmturner/gokrb5#306]
Hi,

Thanks for this package. I was wondering about the following. The test, testenv directories carry a whole bunch of tar files making this a pretty big repository to pull down. Would it be possible to move test, testenv to its own repo?
 
I can see benefits for you as a developer to keep it all together, so I understand if you just want to batch it all together.

**Comment by jerry-tao** [comment]
Without testenv and .git make the repo size from 246M->1M.

**Comment by miekg** [comment]
Thanks!
