### ISSUE TITLE
Dependency on unlicensed / undocumented gofork

### ISSUE THREAD

**Issue by faec** [jcmturner/gokrb5#308]
This library depends on `github.com/jcmturner/gofork` in a couple places:

- `"github.com/jcmturner/gofork/encoding/asn1"` in `asn1tools/tools.go`
- `"github.com/jcmturner/gofork/x/crypto/pbkdf2"` in `crypto/rfc3962/keyDerivation.go`

However that repository has no specified license (except the `LICENSE` file which says it's by the go authors, which seems inaccurate) and I can't find a reason these are used rather than the standard versions. Can this be switched to the standard library? Failing that, could there be more clarity about the reason for the unusual dependency and its license?

**Comment by jcmturner** [comment]
The gofork is a fork of some of the standard library packages where updates have been needed to enable gokrb5 to work. This is why the license has been copied from there.
Details of the updates can be found in the "Known Issues" table at the bottom of the gokrb5 readme. In most cases an issue or PR has been raised against the Go source to have these addressed in the standard library.
