### ISSUE TITLE
kerberos plaintext auth

### ISSUE THREAD

**Issue by yzpnet** [jcmturner/gokrb5#313]
How to use kerberos plaintext auth.

**Comment by yzpnet** [comment]
kerberos plaintext auth is useful.

**Comment by bwmarrin** [comment]
I'd like to have plaintext auth too :)

**Comment by yzpnet** [comment]
Why not to develop this function

**Comment by jcmturner** [comment]
Sorry can you explain more about what you mean by Kerberos plaintext auth. It is not a term I am familiar with.

**Comment by bwmarrin** [comment]
I think he's talking about what I was saying in https://github.com/jcmturner/gokrb5/issues/310

When using Kerberos to sign into a web application.  Normally it can fallback to allowing the user to type in their username/password (in plaintext) for authentication in cases where the Negotiate auth doesn't work automatically.  

This is how the Apache Kerberos authentication module works, but I'm not smart enough about Kerberos or that library to explain it properly.

**Comment by jcmturner** [comment]
Will follow up on #314 so closing this one
