### ISSUE TITLE
udp_preference_limit max value 32700

### ISSUE THREAD

**Issue by wjcaitu** [jcmturner/gokrb5#315]
Hi, 
Why the max value udp_preference_limit is 32700?  when i check MIT document https://web.mit.edu/kerberos/krb5-latest/doc/admin/conf_files/krb5_conf.html#realms, no definition of max value for this parameter is provided. When i set this value to 1000000, the codes report "error processing libdefaults section line (udp_preference_limit = 1000000)"

**Comment by jcmturner** [comment]
Hi, This value mirrors that used in the MIT kerberos. I thought it best to be consistent with this. See:

https://github.com/krb5/krb5/blob/ac8865a22138ab0c657208c41be8fd6bc7968148/src/lib/krb5/os/sendto_kdc.c#L80

I am not sure of the exact reason for this value but I note it is roughly half the max size of a UDP packet.
