### ISSUE TITLE
unsupported EType error

### ISSUE THREAD

**Issue by 29x10** [jcmturner/gokrb5#317]
I am using ticket cache to authenticate with SPNEGO server

Here is my code
``` go
package main

import (
    "gopkg.in/jcmturner/gokrb5.v7/config"
    "gopkg.in/jcmturner/gokrb5.v7/client"
    "gopkg.in/jcmturner/gokrb5.v7/spnego"
    "gopkg.in/jcmturner/gokrb5.v7/credentials"
    "net/http"
    "log"
)


func main() {
     cfg, _ := config.Load("/etc/krb5.conf")
     cred, _:= credentials.LoadCCache("/tmp/krb5cc_user_id")
     cl, _ := client.NewClientFromCCache(cred, cfg)
     r, _ := http.NewRequest("GET", "http://url", nil)
     err := spnego.SetSPNEGOHeader(cl, r, "")
     if (err != nil) {
         log.Println(err)
     }
}
```

could not initialize context: [Root cause: Encrypting_Error] KRBMessage_Handling_Error: TGS Exchange Error: failed to generate a new TGS_REQ < Encrypting_Error: error getting etype to encrypt authenticator: unknown or unsupported EType: 1

`klist -e`
```
Ticket cache: FILE:/tmp/krb5cc_user_id
Default principal: username@realm

Valid starting     Expires            Service principal
08/20/19 10:48:34  08/27/19 10:48:34  krbtgt/realm@realm
	Etype (skey, tkt): DES cbc mode with CRC-32, AES-128 CTS mode with 96-bit SHA-1 HMAC
```

I saw that `aes128-cts-hmac-sha1-96` is supported.

**Comment by jcmturner** [comment]
It looks like the TGT retrieved from the KDC in your case is using AES128_CTS_HMAC_SHA1_96 for the TGT but the session key is using DES_CBC_CRC which is not supported in gokrb5. Check your krb5.conf and what is set for the default_tgs_enctypes field.

**Comment by jcmturner** [comment]
Closing, please re-open if you think there is still an issue.
