### ISSUE TITLE
[Question] HTTP SPNEGO Authentication after kinit

### ISSUE THREAD

**Issue by MisterSpicy** [jcmturner/gokrb5#328]
This is a Question, and not an "issue".

I'm on OSX, and am attempting to write a CLI to operate on a Kerberos enabled Hadoop cluster.  I'm able to access the API through `curl --negotiate -u : <yadda>` after a typical `kinit`, but I can't seem to figure out how to accomplish the same thing using this library.

It seems to use the SPNEGO client I need to create either new credential with passcode, with cache, or with keytab.  I'm not totally sure how curl or Firefox/Chrome do it, but they don't seem to require excess permission beyond the first `kinit`.

If I go through the full `NewClientWithPassword` flow, ask for a password, and do all that, it seems to work, but I'd rather not take the extra steps to keep asking for a password when already kinit-d.

Thanks!

**Comment by MisterSpicy** [comment]
From https://github.com/jcmturner/gokrb5/blob/master/client/client.go#L31

The comment mentions that setting the realm to empty string pulls the realm from the default config.  I do not see anywhere that this actually happens though, and passing empty string throws an error instead.

**Comment by mappu** [comment]
The password (or equivalent-ish, keytab) have a long expiry and are private knowledge.

But the OS has already prompted for them. At OS login, the OS then gets a TGT. The TGT has a short expiry but the OS will usually periodically refresh it throughout the logon session. You can use the TGT from the OS to avoid prompting for the password/keytab.

You can read the TGT on Linux, macOS, and MIT-Kerberos-for-Windows by using the `credentials.LoadCCache` and `client.NewClientFromCCache` functions. The CCache path is normally in the `KRB5CCNAME` environment variable or in some hardcoded per-OS locations.

Native Windows doesn't use the ccache file format, but you can still make use of the TGT via calling the native SSPI library. The https://github.com/dpotapov/go-spnego package wraps gokrb5 to provide "passwordless" SPNEGO using this.

**Comment by MisterSpicy** [comment]
Thanks for the response!

I had considered trying to load the CCache that exists natively on OSX, but it by default uses KCM/API and not a FILE cache, and thus does not have a path I am aware of I can pass to `credentials.LoadCCache`.  OSX also does not set KRB5CCNAME by default.   I could possibly set it, but if I'm going to work around defaults, I may just use the keytab method.

I believe that OSX keeps the key in it's own `Ticket Viewer` from within the Keychain.  Documentation is sparse, but obviously possible since applications like Chrome and Firefox are able to access it.

**Comment by jcmturner** [comment]
@mappu thanks for responding to this. You are right the credentials cache can be one option.
@MisterSpicy there is currently no integration with KCM/API. I am not very familiar with these. Do you have any documentation that could support developing against that?

**Comment by MisterSpicy** [comment]
Documentation appears to be pretty sparse - I've resorted to digging to the implementations in libcurl to try and understand how Heimdal (osx's version of krb5) handles it.  If I come across an answer, I'll post it or file a PR.  Thanks for the response!

**Comment by jcmturner** [comment]
@MisterSpicy I'll close this issue. If you find out more information please reopen. thanks

**Comment by eest** [comment]
Hello,

I was also interested in being able to read a ticket cache on OSX and found this issue. The best overview I have found on the subject of the non-FILE cache used there is this page: https://k5wiki.kerberos.org/wiki/Projects/KCM_client

From the page:
> Heimdal implements a credential cache type named "KCM" where operations are transmitted to a daemon process which manages the actual cache contents. The KCM daemon can be contacted via a Unix domain socket or, on OS X only, via Mach RPC. (There is also incomplete support in the source code for using Doors on Solaris.)
>
> On OS X 10.7 and later, the native default credential cache type uses the KCM protocol via Mach RPC. It is typically referred to via the "API" cache type for continuity with Kerberos for Macintosh; the API and KCM cache types have the same namespace in the native OS X Kerberos.
>
> Kerberos for Windows and Kerberos for Macintosh also implement a daemon-based cache type named "API". It uses a different protocol and transports.

So, a bit confusingly, even if `klist` on a modern OSX machine returns `Credentials cache: API:XXXXXXX` it is actually backed by the heimdal KCM protocol, reinforced in this mailing list thread: http://kerberos.996246.n3.nabble.com/API-cache-on-Mac-OSX-td44391.html
> Apple's API: cache is Heimdal's kcm daemon, which recent (1.13+) MIT
supports as the KCM: ccache type.

As stated there is an added quirk on OSX: while KCM is using UNIX domain sockets on other systems, on OSX it appears to be reached via Mach RPC calls, something I was not at all familiar with prior to investigating this.

The MIT kerberos code supports both, with the implementation found here: 
https://github.com/krb5/krb5/blob/master/src/lib/krb5/ccache/cc_kcm.c
```
/*
 * This cache type contacts a daemon for each cache operation, using Heimdal's
 * KCM protocol.  On macOS, the preferred transport is Mach RPC; on other
 * Unix-like platforms or if the daemon is not available via RPC, Unix domain
 * sockets are used instead.
 */
```

Looking around the heimdal codebase I believe the equivalent code is found here:
https://github.com/heimdal/heimdal/blob/master/lib/ipc/client.c

What I feel most unsure about is how you would interact with the Mach RPC calls from this library, I have not been able to find any obvious native golang way of doing so.
