### ISSUE TITLE
If "dns_lookup_kdc" is true, configured kdc is ignored

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [jcmturner/gokrb5#332]
Per [MIT's documentation on the kerberos conf](https://web.mit.edu/kerberos/krb5-1.12/doc/admin/conf_files/krb5_conf.html), the "dns_lookup_kdc" field is described as:
>Indicate whether DNS SRV records should be used to locate the KDCs and other servers for a realm, **if they are not listed** in the krb5.conf information for the realm.

I am testing with a krb5.conf file like this:
```
[libdefaults]
  ...
  dns_lookup_kdc = true
  ...
[realms]
  MATRIX.LAN = {
    kdc = somewhere.matrix.lan
    ...
  }
```
I'm finding that "somewhere.matrix.lan" isn't attempted. In looking at the code, I've isolated the issue to [here](https://github.com/jcmturner/gokrb5/blob/master/config/hosts.go#L22). This if statement should only be called if there were no kdc's provided _and_ "dns_lookup_kdc" is true.

**Comment by jcmturner** [comment]
Hi, thanks for pointing this out and submitting a PR. I’ll take a look and hopefully merge this shortly. The integration test automation seems to have stopped working so I will need to fix this first.
