### ISSUE TITLE
assumepreauthentication is false after it's set to true

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [jcmturner/gokrb5#335]
It appears that the `client.AssumePreAuthentication(true)` should result in a client with a setting that assumes preauthentication; however, the resulting client still has assume preauthentication set to false.

## Steps to Reproduce

Copy and paste the following test into any `_test.go` file inside the `client` package:
```
package client

import (
	"testing"

	"github.com/jcmturner/gokrb5.v7/config"
	"github.com/jcmturner/gokrb5.v7/keytab"

)

func TestAssumePreauthentication(t *testing.T) {
	t.Parallel()

	cl := NewClientWithKeytab("username", "REALM", &keytab.Keytab{}, &config.Config{}, AssumePreAuthentication(true))
	if !cl.settings.assumePreAuthentication {
		t.Fatal("assumePreAuthentication should be true")
	}
	if !cl.settings.AssumePreAuthentication() {
		t.Fatal("AssumePreAuthentication() should be true")
	}
}
```
Running the test results in the following output:
```
--- FAIL: TestAssumePreauthentication (0.00s)
    client_test.go:14: assumePreAuthentication should be true
```

**Comment by jcmturner** [comment]
Hi, thanks for pointing this out and submitting a PR. I’ll take a look and hopefully merge this shortly.  Looks like it was a copy and paste error. The PR looks good so will merge it but I need to fix the integration test automation which no longer seems to be working.

**Comment by jboelter** [comment]
This introduces a regression in clients that mis-used `AssumePreAuthentication()` (I don't recall why).  Suggest a note in the release notes to annotate that change to use `DisablePAFXFAST()` if that's what the caller intended in the first place :)

````
	cfg, err := config.NewConfigFromString(krb5conf)
	var settings = []func(*client.Settings){
		client.AssumePreAuthentication(true), // Change to DisablePAFXFAST()
	}
	cl := client.NewClientWithPassword(username, realm, password, cfg, settings...)
	r, err := http.NewRequest("GET", "https://example.com/api/v1/token", nil)
	spnegoCl := spnego.NewClient(cl, nil, "")
	resp, err := spnegoCl.Do(r)
````
