### ISSUE TITLE
Handle authentication for clients that send a raw KRB5 token not wrapped in SPNEGO

### ISSUE THREAD

**Issue by jcmturner** [jcmturner/gokrb5#347]
Some clients such as older versions of curl send raw KRB5 tokens that are not wrapped in SPNEGO tokens.

This issue has been raised to split this issue out from others. Please see the original comments and related PRs below for further details. Please use this issue for further discussion on this.

https://github.com/jcmturner/gokrb5/issues/278#issuecomment-482431731

#281
#299

**Comment by jgiannuzzi** [comment]
This issue is fairly easy to reproduce by using the build of cURL bundled in CentOS 6 or 7.

@jcmturner Could you please look at my PR #299 and comment?
