### ISSUE TITLE
Doc for GetChecksumHash method.

### ISSUE THREAD

**Issue by edganiukov** [jcmturner/gokrb5#35]
Hi,
I am trying to understand how to calculate checksum in authenticator for AP_REQ and from current documentation is not really clear what GetChecksumHash (if I understand correct, this method should be used for calculating checksum) method parameters are:
https://github.com/jcmturner/gokrb5/blob/51e436274bbce3ad06339e9359d1a1fc8dc21e85/crypto/etype/etype.go#L26

So:
- not clear what is `protocolKey` parameter?
- if I understand correct, `data` is marshaled data from `messages.Ticket.EncPart`. Ticket got here https://github.com/jcmturner/gokrb5/blob/ab3cf9b73d364620add518ba8fcfaa67a6c37649/client/TGSExchange.go#L64
- what is`usage` parameter? 

Thank you in advance!

**Comment by jcmturner** [comment]
Hi, You are in the guts of the library here. If you are just using one of the etypes implemented you shouldn't need to worry too much about these inner workings. However I will try to answer your bullet points:

- protocolKey: this is the key obtained directly from the keytab or the sessionkey. From this the actual encryption key is derived using a method specific to the etype that also takes in the usage number.
- What the data is depends on what you are trying to achieve. Not sure I have enough to answer this one.
- usage: these are the usage constants as defined in [RFC 4210](https://tools.ietf.org/html/rfc4120#section-7.5.1) you'll find them all at https://github.com/jcmturner/gokrb5/blob/master/iana/keyusage/constants.go

I'm afraid if you are going to operate at this level you'll need to get very familiar with the kerberos RFCs.

You can see how I have created an encrypted authenticator here:
https://github.com/jcmturner/gokrb5/blob/master/messages/APReq.go#L66 which uses the crypto.GetEncryptedData method.

**Comment by edganiukov** [comment]
@jcmturner thank you for the answer.
Actually I was just following README and stuck on checksum calculation - https://github.com/jcmturner/gokrb5/blob/master/README.md#generic-kerberos-client.  
My general goal - authenticate against Kafka Brokers with SASL and GSSAPI described here https://kafka.apache.org/protocol#sasl_handshake. As you see, not really much information about authentication.

**Comment by jcmturner** [comment]
gokrb5 doesn't currently implement SASL but does have some implementation of GSSAPI, that was needed to support SPNEGO, which may be of use to you.

I think what's needed is to implement some of these RFCs
https://tools.ietf.org/html/rfc4752#section-3.1
https://tools.ietf.org/html/rfc4422
