### ISSUE TITLE
Improvement request: export ctxCredentials

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [jcmturner/gokrb5#359]
Hi, just a minor feature request. It would be lovely if this library returned to exporting `ctxCredentials` [here](https://github.com/jcmturner/gokrb5/blob/master/v8/spnego/http.go#L204). We were actually using it [like this](https://github.com/hashicorp/vault-plugin-auth-kerberos/blob/master/path_login.go#L117) to pull out credentials and verify that the identity we received was the one we expected. 

Just posting this here for discussion before dropping in a PR. There may be reasons I'm not aware of that led to it no longer being exported.

**Comment by tyrannosaurus-becks** [comment]
Actually, after some testing I found that in `v8`, instead I can just use `goidentity.CTXKey` for this. Closing as this isn't needed.

**Comment by jcmturner** [comment]
There is this method that can help...

``creds := goidentity.FromHTTPRequestContext(r)``

**Comment by dt** [comment]
Hello!

I wanted to revisit this: if I'm _not_ using http, but using `spnego.AcceptSecContext` directly in another protocol, what's the right way to get the authenticated user's identify? With v7, it looked like I could do `.... reqCtx... = spnego.AcceptSecContext(...)` and then ` reqCtx.Value(spnego.CTXKeyCredentials).(goidentity.Identity)` but with the key unexpected, what's the recommended pattern?
