### ISSUE TITLE
Go complains that methods in config and client packages are invalid

### ISSUE THREAD

**Issue by mastermike501** [jcmturner/gokrb5#360]
Hey Jonathan

I'm quite new to Go and Go modules. Recently bumped up my app (previously working on v7) to use Go modules and also to v8 of gokrb5. However after bumping up the gokrb5 library to v8, the IDE starts complaining that it can't detect `config.NewConfigFromString` and `client.NewClientWithPassword`. Oddly enough, it can detect `spnego.NewClient`. I've attached an image of my imports and also the error that is being returned. I'm wondering if there's something I'm missing?

![image](https://user-images.githubusercontent.com/9069099/73726776-15bcf800-476b-11ea-966b-5d6f9855002f.png)

![image](https://user-images.githubusercontent.com/9069099/73727115-d4791800-476b-11ea-9ef1-67431b6015aa.png)

![image](https://user-images.githubusercontent.com/9069099/73727177-ed81c900-476b-11ea-896f-34f708e86e9d.png)

**Comment by jcmturner** [comment]
I removed some "stutter" in the function names in v8.

So instead of ``config.NewConfigFromString`` it is just ``config.NewFromString``.

Instead of ``client.NewClientWithPassword`` it is ``client.NewWithPassword``.

**Comment by mastermike501** [comment]
Ah…I just realized that there is `client` and `v8/client` in the docs. Totally missed that. Thanks!

Closing issue.
