### ISSUE TITLE
Comments include non-free RFC text

### ISSUE THREAD

**Issue by ssgelm** [jcmturner/gokrb5#374]
While packaging this for Debian it was pointed out to me that chunks of various RFCs are in comments.  As ridiculous as it sounds RFCs are actually not freely redistributable so the comments should probably be removed.  More info at https://www.josefsson.org/bcp78broken/.

**Comment by jcmturner** [comment]
Thanks for bringing this to my attention. I have merged a fix for this.

Can you tell me why Go dependencies are packaged for Debian? Why would these not be managed by Go's own toolchain to download as part of the build process?

Thanks.

**Comment by ssgelm** [comment]
Thanks for the fix!  Debian's whole philosophy regarding packaging is that all dependencies are packaged separately.  The reason for this is that fixing a security vulnerability in a dependency requires only uploading that fix and not updating every single package that depends on it.  For dynamically linked languages this makes a ton of sense, however the nature of Go does mean that every dependency still needs to be rebuilt.  Therefore there are a number of reasons that it is potentially suboptimal for Go, but it's the policy still as it currently stands.  Does my explanation make sense?

**Comment by ssgelm** [comment]
Sorry, another point is that all packages in Debian are expected to be able to be built without internet access.  Obviously vendoring/caching gets around this but that's another reason that we don't just let the Go tooling download dependencies.

**Comment by jcmturner** [comment]
@ssgelm thanks for the explanation. IMHO, I would not package Go dependencies. Rather, only Go built binaries should be packaged. 

As a comparison, what is Debian's approach for Java? Does it package all jars on maven central? I would assume not. 

I'm not convinced it makes sense to package source code like this. As a Go developer I cannot imagine I would use the Debian package of a Go dependency source rather than interact with them via the standard Go toolchain.

**Comment by ssgelm** [comment]
Yes Debian packages all java dependencies separately.  The expectation is that the packaged dependencies are _only_ used for packages.  There's no expectation that a Go developer would opt to use it (in fact I'd definitely recommend against it).  I also agree that it doesn't always make sense but if you look at things at the scale of something like Debian with thousands of packages, having a clearly defined way of determining what packages are affected by a security vulnerability is critical.  To be clear I very much don't make the rules here. :)

**Comment by jcmturner** [comment]
@ssgelm thanks - Just to be clear I was mainly just curious on the approach debian are taking. Thanks for outlining things for me.
