### ISSUE TITLE
Parsing client credentials cache files

### ISSUE THREAD

**Issue by keith6014** [jcmturner/gokrb5#38]
Do you have an example of parsing client credentials cache files with `kinit`?

**Comment by jcmturner** [comment]
If you want to read a kinit credentials cache...
```go
b, err := ioutil.ReadFile("/tmp/krb5cc_1000")
if err != nil {
    panic("Error reading creds cache")
}
c, err := credentials.ParseCCache(b)
if err != nil {
    panic("Error parsing cache")
}
```
A word of warning though, if you have a long running process using these details you'll need to have something updating the cache regularly and you'll need to re-read to ensure that you handle the event of the TGTs expiring (usually after a period of 10-24 hours depending on your environments configuration).
