### ISSUE TITLE
can't load package: .... : no buildable Go source files

### ISSUE THREAD

**Issue by keith6014** [jcmturner/gokrb5#39]
After doing this
`go get gopkg.in/jcmturner/gokrb5.v1`

When I try to import the module.

I keep getting
Can't load package: ... no buildable Go source files.

**Comment by jcmturner** [comment]
You need to import the specific sub packages...

```go
import gopkg.in/jcmturner/gokrb5.v1/<sub pkg>
```
examples:
```go
import gopkg.in/jcmturner/gokrb5.v1/client
import gopkg.in/jcmturner/gokrb5.v1/service
import gopkg.in/jcmturner/gokrb5.v1/credentials
```
