### ISSUE TITLE
KDC dial not looping through rest of KDC's when one of the KDC return an error

### ISSUE THREAD

**Issue by kmhagan** [jcmturner/gokrb5#398]
Hello,

When I perform `client.Login()` with a kerberos configuration file that's last entry is not responding, I receive an error without the client attempting to login with the other KDCs on the list.

working kerb.conf snippet:
```
[realms]
MYKDC.NET = {
 kdc = working-kdc.mykdc.net:88
 master_kdc = working-kdc.mykdc.net:88
 kpasswd = working-kdc.net:464
 kpasswd_server = working-kdc.mykdc.net:464
}
```

not working kerb.conf snippet:
```
[realms]
MYKDC.NET = {
 kdc = working-kdc.mykdc.net:88
 master_kdc = working-kdc.mykdc.net:88
 kpasswd = working-kdc.net:464
 kpasswd_server = working-kdc.mykdc.net:464
 kdc = not-working-kdc.mykdc.net:88
 master_kdc = not-working-kdc.mykdc.net:88
 kpasswd = not-working-kdc.mykdc.net:464
 kpasswd_server = not-working-kdc.mykdc.net:464
}
```

My suggested fix would be the following: https://github.com/kmhagan/gokrb5/commit/75797474f93e9dd4fa1a79b9538164b2f17ca993
Let me know if you agree with the implementation and I can open a PR.

Thank you!

**Comment by jcmturner** [comment]
Thanks I'll take a look at your suggested fix. This seems to be the same issue raised under #324

**Comment by jcmturner** [comment]
Looking at the code around this I may take the opportunity to do some refactoring here...
