### ISSUE TITLE
HTTPServer Decryption Error

### ISSUE THREAD

**Issue by keith6014** [jcmturner/gokrb5#40]
Keep getting SPNEGO Kerberos authentication failed

I have a keytab file which I am able to read thru ktutil. When I do "list" I see all the Principals.

The error message is decrypting encpart of service ticket provided: [KRB Error: (45) KRB_AP_ERR_NOKEY Service key not avaliable - Could not get key from keytab: Matching key not found in keytab. Looking for [HTTP hostname.FDQN] real: REAL.com kvno: 20 etype: 18]

Is there anything else I should be doing?

**Comment by jcmturner** [comment]
Hi, I suspect the issue may be with the kvno in the keytab. The key version number (kvno) gets incremented each time you change the AD account's password. You need to ensure that the keytab has an entry with the same kvno.

To  check this use the ktutil tool (available on Linux not Windows)
```bash
> ktutil
ktutil:  rkt <path to keytab file>
ktutil:  l -e
```

The error message you are seeing means you need to have this in the listing:
```bash
slot KVNO Principal
---- ---- ---------------------------------------------------------------------
   #    20          HTTP/hostname.FQDN@REAL.com (aes256-cts-hmac-sha1-96)
```

**Comment by keith6014** [comment]
what happens if I don't see the matching KVNO? Do I have to ask my AD administrator to create a new keytab with the service id?

**Comment by jcmturner** [comment]
I'm not sure why the kvno command comes back with value of two. The kvno value (20) that appears in the log line comes from the ticket returned from the KDC. 

If you know the password of the AD account that you registered the SPN against in AD you just need to create a keytab with an entry of the correct kvno (20 in your case) for use on the service side.
You can do this with [ktutil](https://web.mit.edu/kerberos/krb5-latest/doc/admin/admin_commands/ktutil.html)

With regards to your two questions:
1) Using a krb5.conf only applies to the client side as the service side does not talk to the KDC. If you are wanting to do this for client then the README.md gives details on how to do this.
2) Ignoring the kvno would not be a correct implementation. You are best to put the service side credentials in the keytab with the kvno that matches what the KDC sends.

**Comment by keith6014** [comment]
Yes, I have the password for the service account. 

I am not familiar with Kerberos. 

Correct me if I am wrong, I don't think ktutil can create service principals (HTTP/server.org). I think thats done in ktadmin, correct?

**Comment by jcmturner** [comment]
You are not trying to create a service principal. You are just trying to create a [keytab](https://web.mit.edu/kerberos/krb5-latest/doc/basic/keytab_def.html). Keytabs are basically a format for holding passwords so you are just trying to create one that holds the password for the AD account you have registered the SPN against. You need to add entries to the keytab using the correct enctype and kvno.

**Comment by jcmturner** [comment]
Hi, were you able to get this working?

**Comment by jcmturner** [comment]
I'm going to close this issue, assuming you were able to resolve this.
