### ISSUE TITLE
gollvm support

### ISSUE THREAD

**Issue by advancedwebdeveloper** [jcmturner/gokrb5#410]
Hi.
I was able to build all the source code and tried to run all tests, using [gollvm](https://go.googlesource.com/gollvm/) .
Probably you can update your README and add gollvm into the list of supported compilers.

> $ go version
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64

**Comment by jcmturner** [comment]
@advancedwebdeveloper thanks for this I've made a note in the readme.

**Comment by advancedwebdeveloper** [comment]
CC @thanm @cherrymui @ianlancetaylor

I think there have to be some way to mark descriptions of projects, so that it would be clear whether they could be compiled with llvm-goc.
It could allow to search those on Github.
