### ISSUE TITLE
使用gokbr5连接hbase集群报错，什么原因

### ISSUE THREAD

**Issue by yuanpengpeng** [jcmturner/gokrb5#414]
使用gokbr5连接hbase集群报错

代码：
ktFromFile, err := keytab.Load("/home/transwarp/sophon.keytab")
	if err!=nil{
		log.Printf("err1 output:%+v",err)
	}
	log.Printf("ktFormFile output:%+v",ktFromFile)

	cfg, err := config.Load("/media/transwarp/Newsmy/config-hyperbase1/krb5.conf")
	if err!=nil{
		log.Printf("err2 output:%+v",err)
	}
	log.Printf("cfg output:%+v",cfg)

	//cl := client.NewClientWithPassword("username", "REALM.COM", "password", cfg)
	cl := client.NewClientWithKeytab("hbase/tw-node42@TDH", " tw-node42", ktFromFile, cfg)
	err = cl.Login()
	if err!=nil{
		log.Printf("err3 output:%+v",err)
	}

错误日志：
2020/11/13 13:02:54 ktFormFile output:&{version:2 Entries:[{Principal:{NumComponents:2 Realm:TDH Components:[hive tw-node41] NameType:1} Timestamp:2020-09-16 10:47:04 +0800 CST KVNO8:0 Key:{KeyType:16 KeyValue:[32 196 79 11 7 185 218 162 214 21 22 55 37 167 254 182 47 158 140 103 155 122 109 134]} KVNO:0} {Principal:{NumComponents:2 Realm:TDH Components:[hive tw-node41] NameType:1} Timestamp:2020-09-16 10:47:04 +0800 CST KVNO8:0 Key:{KeyType:18 KeyValue:[15 247 207 127 11 88 206 107 131 193 125 13 250 166 93 38 15 21 19 246 97 193 75 72 163 134 124 221 43 88 235 65]} KVNO:0} {Principal:{NumComponents:2 Realm:TDH Components:[hive tw-node41] NameType:1} Timestamp:2020-09-16 10:47:04 +0800 CST KVNO8:0 Key:{KeyType:3 KeyValue:[167 93 199 241 87 74 131 104]} KVNO:0} {Principal:{NumComponents:2 Realm:TDH Components:[hive tw-node41] NameType:1} Timestamp:2020-09-16 10:47:04 +0800 CST KVNO8:0 Key:{KeyType:17 KeyValue:[217 121 119 251 100 53 199 158 118 30 223 153 240 131 214 252]} KVNO:0} {Principal:{NumComponents:2 Realm:TDH Components:[hive tw-node41] NameType:1} Timestamp:2020-09-16 10:47:04 +0800 CST KVNO8:0 Key:{KeyType:23 KeyValue:[125 126 159 153 252 142 30 66 48 183 102 222 211 59 234 107]} KVNO:0}]}

2020/11/13 13:02:54 cfg output:&{LibDefaults:{AllowWeakCrypto:true Canonicalize:false CCacheType:4 Clockskew:5m0s DefaultClientKeytabName:/usr/local/var/krb5/user/0/client.keytab DefaultKeytabName:/etc/krb5.keytab DefaultRealm:TDH DefaultTGSEnctypes:[aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 des3-cbc-sha1 arcfour-hmac-md5 camellia256-cts-cmac camellia128-cts-cmac des-cbc-crc des-cbc-md5 des-cbc-md4] DefaultTktEnctypes:[aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 des3-cbc-sha1 arcfour-hmac-md5 camellia256-cts-cmac camellia128-cts-cmac des-cbc-crc des-cbc-md5 des-cbc-md4] DefaultTGSEnctypeIDs:[18 17 23] DefaultTktEnctypeIDs:[18 17 23] DNSCanonicalizeHostname:true DNSLookupKDC:false DNSLookupRealm:false ExtraAddresses:[] Forwardable:true IgnoreAcceptorHostname:false K5LoginAuthoritative:false K5LoginDirectory:/root KDCDefaultOptions:{Bytes:[0 0 0 16] BitLength:32} KDCTimeSync:1 NoAddresses:true PermittedEnctypes:[aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 des3-cbc-sha1 arcfour-hmac-md5 camellia256-cts-cmac camellia128-cts-cmac des-cbc-crc des-cbc-md5 des-cbc-md4] PermittedEnctypeIDs:[18 17 23] PreferredPreauthTypes:[17 16 15 14] Proxiable:false RDNS:true RealmTryDomains:-1 RenewLifetime:168h0m0s SafeChecksumType:8 TicketLifetime:24h0m0s UDPPreferenceLimit:1465 VerifyAPReqNofail:false} Realms:[{Realm:TDH AdminServer:[] DefaultDomain: KDC:[tw-node41:1088 tw-node42:1088] KPasswdServer:[] MasterKDC:[]}] DomainRealm:map[]}

2020/11/13 13:02:54 err3 output:[Root cause: Networking_Error] Networking_Error: AS Exchange Error: failed sending AS_REQ to KDC: failed to communicate with KDC. Attempts made with UDP (no KDCs defined in configuration for realm  tw-node42) and then TCP (no KDCs defined in configuration for realm  tw-node42)
ERRO[0014] failed looking up region                      backoff=16ms err="failed to read the /hbase/master znode: zk: client authentication failed" key="\"\"" table="\"\""
ERRO[0014] failed looking up region                      backoff=32ms err="failed to read the /hbase/master znode: zk: client authentication failed" key="\"\"" table="\"\""
ERRO[0014] failed looking up region                      backoff=64ms err="failed to read the /hbase/master znode: zk: client authentication failed" key="\"\"" table="\"\""
ERRO[0014] failed looking up region                      backoff=128ms err="failed to read the /hbase/master znode: zk: client authentication failed" key="\"\"" table="\"\""
ERRO[0014] failed looking up region                      backoff=256ms err="failed to read the /hbase/master znode: zk: client authentication failed" key="\"\"" table="\"\""

**Comment by jcmturner** [comment]
from the following in the logs it looks like a configuration issue. You have not defined the KDCs to use for the realm.

> no KDCs defined in configuration for realm tw-node42
