### ISSUE TITLE
KDC did not respond appropriately to FAST negotiation

### ISSUE THREAD

**Issue by dpotapov** [jcmturner/gokrb5#42]
Hi,

I'm receiving following error when trying to obtain TGT with `client.Login()` in ActiveDirectory environment:

```
[Root cause: KRBMessage_Handling_Error] KRBMessage_Handling_Error: AS Exchange Error: AS_REP is not valid < KRBMessage_Handling_Error: KDC did not respond appropriately to FAST negotiation
```

Commenting out those line in `KDCRep.go` helps, but, of course, it is not a solution:
```
if len(k.DecryptedEncPart.EncPAData) < 2 || !k.DecryptedEncPart.EncPAData.Contains(patype.PA_FX_FAST) {
	return false, krberror.NewErrorf(krberror.KRBMsgError, "KDC did not respond appropriately to FAST negotiation")
}
```
Debugger shows that `k.DecryptedEncPart.EncPAData` has 1 element with `PADataType = 149`.

Thanks.

**Comment by jcmturner** [comment]
You can explicitly turn off FAST on your client...

```go
client.GoKrb5Conf.DisablePAFXFast = true
```

**Comment by dpotapov** [comment]
Thanks, it works! Are the any implications of doing so?
Anyway closing the issue...
