### ISSUE TITLE
Multi-realm service ticket issue

### ISSUE THREAD

**Issue by dpotapov** [jcmturner/gokrb5#43]
Hi,

I'm trying to authenticate to a web service in a different Realm other than client:
```
// krb5.conf has a default realm AAA.CORP.COM and all other realms under [realms] section
cfg, err := config.Load("C:\\krb5.conf")
cl := client.NewClientWithPassword("user", "AAA.CORP.COM", "password")
cl.WithConfig(cfg)
r, _ := http.NewRequest("GET", "https://service.bbb.corp.com/", nil)
cl.SetSPNEGOHeader(r, "HTTP/service.bbb.corp.com")
```
Request fails with 401 - Unauthorized error.

If I use client's credential in `bbb.corp.com` realm - everything works.

I was trying also to specify full SPN for a web service like this:
```
cl.SetSPNEGOHeader(r, "HTTP/service.bbb.corp.com@BBB.CORP.COM")
```
does not work either.

Thanks.

**Comment by jcmturner** [comment]
Do you get an error if you...

```go
err := cl.SetSPNEGOHeader(r, "HTTP/service.bbb.corp.com@BBB.CORP.COM")
if err != nil {
    fmt.Println(err.Error())
}
```

What version of gokrb5 are you using? I recently made some updates to work with referrals so if you are using an old version you may not be using that.

**Comment by dpotapov** [comment]
ok, printing the error message gives an answer:
```
KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type
```
I've fixed this by putting correct list of enctypes to my krb5.conf.

Thanks a lot!

PS: I'm using latest v2 code
