### ISSUE TITLE
KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type

### ISSUE THREAD

**Issue by LCTDDL** [jcmturner/gokrb5#430]
[Root cause: KDC_Error] KDC_Error: AS Exchange Error: kerberos error response from KDC: KRB Error: (14) KDC_ERR_ETYPE_NOSUPP KDC has no support for encryption type - BAD_ENCRYPTION_TYPE

      "des-cbc-crc",
      "des3-cbc-sha1"

**Comment by jcmturner** [comment]
des3-cbc-sha1-kd is supported. As @jake-scott states DES algorithms are not considered that strong and I would encourage you to configure for a more modern algorithm.
