### ISSUE TITLE
krb5conf: parsing auth_to_local with RULE syntax

### ISSUE THREAD

**Issue by dpotapov** [jcmturner/gokrb5#44]
Hello,

krb5conf fails to parse `[realms]` section with auth_to_local RULE definition like:
```
    auth_to_local = RULE:[1:$1@$0](.*@EXAMPLE.COM)s/.*//
```

It seems the root cause is square brackets, which are interpreted as a new section definition.

**Comment by jcmturner** [comment]
The krb5conf doesn't support rules but I'll update to ensure they don't make the parsing error.
