### ISSUE TITLE
Using gokrb5 for other than http

### ISSUE THREAD

**Issue by keith6014** [jcmturner/gokrb5#462]
I have gokrb5 working for HTTP SPN authentication. I would like to create something more generic. I would like to build a proxy service which can be used for PostgreSQL (obviously not running on PostgreSQL port). I want to build a service as a test bed not for production. Is that possible?

**Comment by jcmturner** [comment]
https://github.com/jcmturner/gokrb5/blob/master/v8/USAGE.md covers how to create a generic client and service.
