### ISSUE TITLE
klist 

### ISSUE THREAD

**Issue by keith6014** [jcmturner/gokrb5#48]
When using the gokrb5 libarary, how come the ticket and SPN doesn't show up in `klist`?

When I do a klist first, I see my credential cache, then I do a curl -u --negotiate u: http://foo.org and I authentication. Then when i do a klist I see the credential again. Howwever, when I use gokrb5 I don't see it.

Btw, the client library works, just curious why I don't see the certificate.

**Comment by jcmturner** [comment]
klist is a utility that reads the credentials cache at /tmp/krb5cc_$(id -u $(whoami))

These are OS level integrations and utilities. 

Gokrb5 does not store details in this OS cache as it should not be tightly coupled to the OS. Gokrb5 could be used on windows where this cache file does not exist.
