### ISSUE TITLE
config read error

### ISSUE THREAD

**Issue by kahnert** [jcmturner/gokrb5#5]
gokrb5/config can't read empty lines within a section nor configs containing "v4_name_convert", see http://web.mit.edu/quentin/krb5-config/krb5.conf

**Comment by jcmturner** [comment]
Fix has been merged for empty line.
I'm not intending to support v4 configs at this time. A more friendly error message should now be given if these are used. I'm not sure if "v4_name_convert" is still a valid as it is not listed at [https://web.mit.edu/kerberos/krb5-latest/doc/admin/conf_files/krb5_conf.html](https://web.mit.edu/kerberos/krb5-latest/doc/admin/conf_files/krb5_conf.html)
