### ISSUE TITLE
Active directory authentication works but not sure what to do next

### ISSUE THREAD

**Issue by keith6014** [jcmturner/gokrb5#506]
I am able to get the [groupSIDs](https://github.com/jcmturner/gokrb5/blob/663478bf457f1fc3275973bea5b7b787cd332015/v8/credentials/credentials.go#L67). There are 1000+ of them in the list. But, how does one translate a human group like "MyGroupA" to "S-..." ?

**Comment by jcmturner** [comment]
I think the only way to do this is via an LDAP query
