### ISSUE TITLE
KDC_ERR_C_PRINCIPAL_UNKNOWN when login as a user in non-default Realm

### ISSUE THREAD

**Issue by dpotapov** [jcmturner/gokrb5#51]
Hi,

I'm receiving following error if I perform `client.Login()` for a user with realm that not matching `default_realm` in configuration:

```
[Root cause: Encoding_Error] Encoding_Error: AS Exchange Error: failed to process the AS_REP: [KRB Error: (6) KDC_ERR_C_PRINCIPAL_UNKNOWN Client not found in Kerberos database]
```

**Comment by jcmturner** [comment]
@dpotapov could you test this again with the latest version. There have been some fixes in this area that may have addressed this. I want to confirm if you are still seeing the issue.
Thanks.

**Comment by dpotapov** [comment]
Hi,
I've got a new after updating to a latest version:
```
Login: [Root cause: Encoding_Error] Encoding_Error: AS Exchange Error: failed to process the AS_REP < Encoding_Error: Failed to unmarshal KDC's reply: [asn1: structure error: explicitly tagged member didn't match]
```

**Comment by dpotapov** [comment]
Please ignore my previous post, since unmarshaling issue is related to 5cf868a24ea32b3d89fa06004db9fcb20601f586.

The original issue still persists in latest version.

**Comment by jcmturner** [comment]
@dpotapov Do you see that your pull request (#60) resolves things in this issue for you? I'll take a look at the PR and if all looks good I'll merge and close this issue.

**Comment by jcmturner** [comment]
I'm closing this issue. I think that when doing the login (AS_REQ) you have to target the KDC for the realm the user is in directly. So this error is expected if you are not talking to the domain that has this user.
