### ISSUE TITLE
Getting valid service KVNO

### ISSUE THREAD

**Issue by Sireax** [jcmturner/gokrb5#514]
Greetings! Can I get a valid service kvno using ASExchange method, or something else? Now it is returning either 0 or 5.

**Comment by jcmturner** [comment]
The AS response returns the PVNO (Protocol Version Number) not the KVNO. PVNO should always be 5 in this implementation. Seeing 0 may be a bug that needs addressing.

**Comment by jcmturner** [comment]
I think you can get the KVNO from an ASExchange it should be in `ASRep.Ticket.EncPart.KVNO`
