### ISSUE TITLE
Trouble authenticating against Windows 2012r2

### ISSUE THREAD

**Issue by bodgit** [jcmturner/gokrb5#58]
Here's my test client that I'm trying to get working against my Windows 2012r2 AD environment which I figure should be the bare minimum that should  work:
```golang
package main

import "gopkg.in/jcmturner/gokrb5.v2/config"
import "gopkg.in/jcmturner/gokrb5.v2/client"
//import "gopkg.in/jcmturner/gokrb5.v2/keytab"
import "log"
import "os"

func main() {
        l := log.New(os.Stderr, "GOKRB5 Client: ", log.Ldate|log.Ltime|log.Lshortfile)

        cfg, err := config.Load("/etc/krb5.conf")
        if err != nil {
                l.Printf("Error on config: %v\n", err)
        }

        //kt, err := keytab.Load("/home/user/nsupdate.keytab")
        //if err != nil {
        //        l.Printf("Error on keytab: %v\n", err)
        //}

        cl := client.NewClientWithPassword("user", "EXAMPLE.COM", "password")
        cl.WithConfig(cfg)
        err = cl.Login()
        if err != nil {
                l.Printf("Error on AS_REQ: %v\n", err)
        }
}
```
With this I get the error ` Error on AS_REQ: [Root cause: Encrypting_Error] KRBMessage_Handling_Error: AS Exchange Error: failed setting AS_REQ PAData for pre-authentication required < Encrypting_Error: Error creating etype: [Unknown or unsupported EType: 26]`. Looking up EType 26 suggests it's one of the Camellia ciphers `camellia256-cts-cmac` (defined in RFC 6803), I'm a bit suprised as all my searching suggests Windows doesn't support that.

I've found if I edit the user in AD and tick the option `Do not require Kerberos preauthentication` then I get this different error `Error on AS_REQ: [Root cause: KRBMessage_Handling_Error] KRBMessage_Handling_Error: AS Exchange Error: AS_REP is not valid < KRBMessage_Handling_Error: KDC did not respond appropriately to FAST negotiation`. Now I'm a bit stuck. I'd like to eventually use a keytab but for now I'm just trying to get it passing with a password.

Ultimately, I'm trying to work out if it's possible to use your library along with `github.com/miekg/dns` to be able to perform GSS-TSIG DNS updates to a Windows DNS/AD server as they don't support normal key-based TSIG updates like BIND does or otherwise require you to turn off secure DNS updates altogether, which won't be an option. I can currently do this manually with a combination of `ktutil`, `kinit` and `nsupdate -g` but I would like a Go equivalent.

You might be able to tell me straight off if your library has enough of the GSSAPI implemented for me to even do that.

**Comment by jcmturner** [comment]
@bodgit can you provide the /etc/krb5.conf contents. I suspect you may be specifying an enctype in there that gokrb5 does not support.

The error ```KDC did not respond appropriately to FAST negotiation``` can be resolved by adding the following line just before the Login() line. 
```go
cl.GoKrb5Conf.DisablePAFXFast = true
```
I should add this to the readme as a common thing that needs to be done for AD KDCs.

I don't know how the authentication exchange for the ```nsupdate -g``` works. Does it definitely use GSSAPI?

**Comment by bodgit** [comment]
> can you provide the /etc/krb5.conf contents. I suspect you may be specifying an enctype in there that gokrb5 does not support.

Here it is:
```
[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 dns_lookup_realm = true
 dns_lookup_kdc = true
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true
 rdns = false
 default_ccache_name = FILE:/tmp/krb5cc_%{uid}
 default_realm = EXAMPLE.COM

[realms]
 EXAMPLE.COM = {
kdc = ad1.example.com
kdc = ad2.example.com
 }

[domain_realm]
 example.com = EXAMPLE.COM
 .example.com = EXAMPLE.COM
```
> I don't know how the authentication exchange for the nsupdate -g works to be able to answer if there is enough GSSAPI implementation to cover it. Looks like it would need some research into https://tools.ietf.org/html/rfc3645

Sorry, yes, I should have mentioned it is RFC 3645. I've done a quick scan of it and it seems for the client side of things, I need the equivalent of `GSS_Init_sec_context()`  and then `GSS_GetMIC()` and/or `GSS_VerifyMIC()`. Section 3 in the RFC covers the initial client side of the negotiation.

**Comment by jcmturner** [comment]
So I implemented the krb5.conf parsing in line with the documentation here: https://web.mit.edu/kerberos/krb5-latest/doc/admin/conf_files/krb5_conf.html

As documented there the default enctypes if you don't specify them are:
```aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 aes128-cts-hmac-sha256-128 aes256-cts-hmac-sha384-192 des3-cbc-sha1 arcfour-hmac-md5 camellia256-cts-cmac camellia128-cts-cmac des-cbc-crc des-cbc-md5 des-cbc-md4```

I did this a while back and thinking about it in light of this perhaps gokrb5 should default to the enctypes it supports. I'll probably make that change.

So if you specify ```default_tgs_enctypes``` and ```default_tkt_enctypes``` in your krb5.conf I think this should getting it working for you. Something like...
```
default_tgs_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 des3-cbc-sha1-kd rc4-hmac
default_tkt_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 des3-cbc-sha1-kd rc4-hmac
```

**Comment by bodgit** [comment]
If I don't also prune `rc4-hmac` from that list, I get this error:
```
GOKRB5 Client: 2017/11/27 15:29:39 test.go:29: Error on AS_REQ: [Root cause: Encrypting_Error] KRBMessage_Handling_Error: AS Exchange Error: failed setting AS_REQ PAData for pre-authentication required < Encrypting_Error: Error getting key from credentials: [Error deriving key from string: Invalid s2kparams length]
```
Other than that, my test client now logs in successfully provided I add the `cl.GoKrb5Conf.DisablePAFXFast = true` as you indicated.

**Comment by jcmturner** [comment]
@bodgit To address this issue I'm going to filter out unsupported enctypes when the krb5.conf is parsed (a pretty easy update). I have raised #61 to cover the issue seen when using rc4-hmac as this is a different problem as this will require some more investigation.
