### ISSUE TITLE
Guidance on "kinit"-lite behavior

### ISSUE THREAD

**Issue by benclarkwood** [jcmturner/gokrb5#62]
Howdy!

I need to bundle something cross-platform that can serve the most basic function of Kinit, specifically, getting a TGT from the KDC and putting it in the ticket cache. 

Is it easy to either combine or modify elements of this library to mimic that behavior? It appears that all TGT caching occurs within the go process.

**Comment by jcmturner** [comment]
Yes all ticket caching happens in the go process as there are OS tools that already do caching to files etc. The idea of this library is for use in Go applications so it's not in scope to do things at the OS level. That said you could write your own "kinit" using this library and write to a cache file yourself. There is no cross platform cache file format so you'd probably have to define something yourself.
