### ISSUE TITLE
How do I use an existing ticket in the credentials cache with SPNEGO?

### ISSUE THREAD

**Issue by F21** [jcmturner/gokrb5#7]
First off, thank you so much for creating this library! 😄 

I have a usecase where I have an existing ticket (the user has performed a kerberos login elsewhere) and the ticket is available in the credentials cache at this location: `/tmp/krb5cc_$(id -u $(whoami))`.

Do you have an example of using the ticket to authenticate and make requests against a HTTP service using SPNEGO?

**Comment by jcmturner** [comment]
Hi, I'm glad people are getting some value out of the library!

I've had a quick google for the format of the ticket cache and have not been able to find any documentation of it so it may be tricky to figure out how to do this. I'll keep digging. If you know where I can find this information please let me know and I can take a look.

The README.md has details on how to get a client to talk to an SPNEGO HTTP web service. See the "Kerberos Client" section. In summary you follow these steps:

1. Create the client from a password or keytab (if I can find how to use the ticket cache I can add to the options here.
2. Configure the client by passing a config.Config instance to the clients WithConfig() method
3. Login the client
4. Create a http request (golang's net/http package)
5. Pass the request instance to the client's SetSPNEGOHeader method
6. Do the request as you normally would with the net/http package

Hope this helps...

**Comment by F21** [comment]
hey @jcmturner 

From some quick googling, this appears to document the format of the credentials cache: https://web.mit.edu/kerberos/krb5-1.13/doc/formats/ccache_file_format.html

I am not too familiar with AD on Windows, so I do not know if it support a credentials cache.

As for SPNEGO, I'd love to have an option to use it with the credentials in the credentials cache.

For example, the user has logged in using `kinit` or some other method and has the ticket in the credentials cache. I'd then like to use that existing ticket to log in to a resource secured by SPNEGO rather than asking gokrb5 to perform the login.

**Comment by jcmturner** [comment]
You should now be able to do the following...

Load the credential cache:
ccache, err := credentials.LoadCCache("/tmp/krb5cc")

Create a client from the loaded CCache
cl, err := NewClientFromCCache(ccache)

Now do the SPNEGO request
r, _ := http.NewRequest("GET", "http://host.test.gokrb5/index.html", nil)
cl.SetSPNEGOHeader(r, "")
HTTPResp, err := http.DefaultClient.Do(r)

**A word of warning** if you don't add a keytab or password to the client and turn on the renewal of the TGT then after a number of hours (when the TGT expires) you will start to get auth failures. Without a password or a keytab the TGT cannot be re-requested. 

To do this...
cl.WithKeytab(keytab)
cl.EnableAutoSessionRenewal()

Alternatively if you have an external component refreshing the credential cache file then you will need to regularly recreate the client from a freshly loaded credential cache.

I have done some rudimentary testing of this and it appears to work. Let me know if you have any issues.

**Comment by F21** [comment]
Super awesome! Thank you so much @jcmturner ! 👍
