### ISSUE TITLE
leverage github.com/zhuangsirui/binpacker [SUGGESTION]

### ISSUE THREAD

**Issue by jasonwbarnett** [jcmturner/gokrb5#76]
Would it make sense to replace your `readIntX` methods with a library like this: https://github.com/zhuangsirui/binpacker

It seems much easier to maintain and read.

**Comment by jasonwbarnett** [comment]
or even something like this: https://github.com/lunixbochs/struc

**Comment by jcmturner** [comment]
Thanks I'll take a look. However I have been trying to avoid dependencies other than the Go standard library.
