### ISSUE TITLE
building on 32-bit system with GOARCH=386 is broken again?

### ISSUE THREAD

**Issue by dpotapov** [jcmturner/gokrb5#81]
Hi,

I saw there was an issue recently closed about building on 32-bit systems. Just tried to test it and it seems there is an error still:

```bash
$ GOARCH=386 go build gopkg.in/jcmturner/gokrb5.v3/crypto
# gopkg.in/jcmturner/gokrb5.v3/crypto
../go/src/gopkg.in/jcmturner/gokrb5.v3/crypto/crypto.go:61: constant 4294967158 overflows int
```

Would be good to have a fix.
Thanks.

**Comment by jcmturner** [comment]
I have been giving this some thought and it may require some more refactoring than it would first appear.

Documentation for the Go ASN1 library says it only marshals/unmarshals integers into int, int32 and int64 and not unsigned ints. The RFC often refers to values as uint32 which would overflow an int on a 32bit system. Therefore I might need to change some ints in the kerberos types into int64s which may be a little confusing given the RFC states uint32 but these would not be overflowed on a 32bit system by high uint32 values.

Any way, I will give this some attention and also add a travis test to ensure things remain working on 32bit systems.

**Comment by jcmturner** [comment]
Hi, I believe I have resolved issues for 32bit systems in the code on branch issue-81.
It would be good if you could test and confirm it works for you. Then I can merge to master and create a release. Thanks.

**Comment by dpotapov** [comment]
Hi,
I've tested building with GOARCH=386 on 64-bit linux - it works.
