### ISSUE TITLE
Keytab and Kvno

### ISSUE THREAD

**Issue by sambott** [jcmturner/gokrb5#85]
Great library @jcmturner 

I'm having a little trouble with selecting keys from the keytab on the client side, because you have to know the correct KVNo ahead of time. Which is, of course, possible to lookup but is a little fiddly.

I couldn't see in the RFC what is the suggested approach for this, but generally when using krb5 libraries you just create a keytab entry with a kvno of (say) 1 and everything works.

Haven't seen the mechanism other libraries are taking around this, not sure if you're away of any? One possible solution would be to take newest key of the correct principal and cipher suite if an exact match including the version failed at keytab.go:52?

Happy to raise a PR, but would like your view first.

**Comment by jcmturner** [comment]
Can you provide an example of a library that does this as it will help me look into it. I generally prefer not to take implicit actions as this can lead to confusion when there are issues as root causes get masked. However I can take a look at what other libraries do and consider it.
