### ISSUE TITLE
Cannot connect to KDC from client

### ISSUE THREAD

**Issue by MadOtis** [jcmturner/gokrb5#96]
ok, so I caveat this with "I'm new to Krb5 authentication" and "Its likely a misconfiguration on my end".  I have a need to set up a simple Kerberos token mechanism in order to connect a Go microservice running in a linux docker container to an MS SQL Server that requires a domain login.

I have a dedicated domain "service account" that can successfully log in using kinit via command-line, however, using the same credentials in the following code-snippet produces:

```[Root cause: Networking_Error] Networking_Error: AS Exchange Error: failed sending AS_REQ to KDC: failed to communicate with KDC. Attempts made with UDP (no KDCs defined in configuration for realm ) and then TCP (no KDCs defined in configuration for realm )```

The snippet of code is:
```
	cfg, err := config.Load("/etc/krb5.conf")
	if err != nil {
	    logger.Log("Error", err)
        }
	cl := client.NewClientWithPassword(userCreds.kdcLogin, kdcDomain, userCreds.kdcPasswd)
	cl.WithConfig(cfg)
	if err := cl.Login(); err != nil {
	    logger.Log("Error", err)
        }
```

It doesn't seem to make any difference if my userCreds.kdcLogin contains "my_service_account@DOMAIN.COM" or "my_service_account" (sans '@domain').

Again, I CAN log in via CLI using kinit with the credentials specified, but when running it via the GoLang microservice, I can't successfully log in.

If it helps, here is a paste of my /etc/krb5.conf file:
```
[libdefaults]
dns_lookup_realm = false
ticket_lifetime = 24h
renew_lifetime = 7d
forwardable = true
rdns = false
default_realm = WINDOWSKDCDOMAIN
default_ccache_name = KEYRING:persistent:%{uid}

[realms]
WINDOWSKDCDOMAIN = {
kdc = MYDC.MYCOMPANY.COM:88
}
```

I've tried this WITH and WITHOUT domain_realm section, and it makes ZERO difference.

**Comment by jcmturner** [comment]
Did you edit the error message to remove the realm name before posting? If not then I think that the kdcDomain you are passing into NewClientWithPassword may be equal to "".

Another possibility is that your krb5.conf looks a little odd. I think you want it to be:
```
[libdefaults]
  default_realm = DOMAIN.COM
  dns_lookup_realm = false
  dns_lookup_kdc = false
  ticket_lifetime = 24h
  forwardable = yes
  default_tkt_enctypes = aes256-cts-hmac-sha1-96
  default_tgs_enctypes = aes256-cts-hmac-sha1-96

[realms]
 DOMAIN.COM = {
  kdc = MYDC.MYCOMPANY.COM:88
 }
```
You may need to change the default enctypes for what your domain supports.

**Comment by jcmturner** [comment]
Hi, did you get this working OK? If so, I'll close this issue.
