### ISSUE TITLE
Cannot SPNEGO to hosts whose credentials exist in the ccache

### ISSUE THREAD

**Issue by dkfitbit** [jcmturner/gokrb5#99]
# Setup

```go
cfg, _ := config.NewConfigFromString("...")
cc, _ := credentials.LoadCCache("/tmp/krb5cc_1000")
k5cli, _ := client.NewClientFromCCache(cc)
k5cli.WithConfig(cfg)

req, _ := http.NewRequest("GET", "https://example.com/endpoint", nil)
k5cli.SetSPNEGOHeader(req, "HTTP/example.com")
```

KDC, kinit, and gokrb5 are all choosing aes256-cts-hmac-sha1-96 encryption (etype 18).

Tested against v2.1.2 and v4.1.1. Go version is go1.10 linux/amd64.

# Expected behavior

Uses existing cached ticket for "HTTP/example.com" if one exists in ccache.

Uses TGT to obtain "HTTP/example.com" ticket if no existing ticket in ccache.

# Actual behavior

Works fine if ccache contains TGT and nothing else.

Fails with following error when trying to use cached ticket:

```
[Root cause: Encoding_Error] Encoding_Error: cound not generate SPNEGO negotiation token: Could not create NegTokenInit: error getting MechToken; [Root cause: Encrypting_Error] KRBMessage_Handling_Error: Error creating Authenticator for AP_REQ < Encrypting_Error: Error encrypting Authenticator: Error encrypting data: Incorrect keysize: expected: 32 actual: 0
```

Proximate cause is that encryptAuthenticator in messages/APReq.go has usage values defined for `nametype.KRB_NT_PRINCIPAL` and for `nametype.KRB_NT_SRV_INST`, but not for `nametype.KRB_NT_SRV_HST`. This causes usage to equal 0, which causes EncryptMessage in crypto/rfc3962/encryption.go to use a nil derived key.

Unfortunately, I do not understand enough about the Kerberos protocol to propose an actual fix.

## More details

Running `klist -ef` shows (with redactions):

```
Ticket cache: FILE:/tmp/krb5cc_1000
Default principal: dking@CORP.REALM

Valid starting       Expires              Service principal
03/07/2018 11:37:54  03/07/2018 21:37:54  krbtgt/CORP.REALM@CORP.REALM
        renew until 03/08/2018 11:37:47, Flags: FPRIA
        Etype (skey, tkt): aes256-cts-hmac-sha1-96, aes256-cts-hmac-sha1-96 
03/07/2018 11:38:44  03/07/2018 21:37:54  krbtgt/PROD.REALM@CORP.REALM
        renew until 03/08/2018 11:37:47, Flags: FPRAO
        Etype (skey, tkt): aes256-cts-hmac-sha1-96, aes256-cts-hmac-sha1-96 
03/07/2018 11:38:44  03/07/2018 21:37:54  HTTP/example.com@PROD.REALM
        renew until 03/08/2018 11:37:47, Flags: FPRAT
        Etype (skey, tkt): aes256-cts-hmac-sha1-96, aes256-cts-hmac-sha1-96 
```

CORP.REALM is a Windows AD DC, PROD.REALM is an MIT KDC (krb5-kdc on Ubuntu).

**Comment by jcmturner** [comment]
I'm writing some integration tests around CCache to help with this one.

I notice that you are doing this...
```go
cfg, _ := config.NewConfigFromString("...")
```
This is not a valid krb5 config so if there is a TGT in the cache the client won't have the configuration needed to know where the KDC to obtain a service ticket.

Nevertheless the client should have able to use a ticket in the CCache if it is already present and still valid so I will look into this.

**Comment by jcmturner** [comment]
I have written some tests to cover this but I am not getting the issue you are.

The tests written are:
https://github.com/jcmturner/gokrb5/blob/bc57e566151da508625884ff2463482f98301fd5/client/client_integration_test.go#L557
https://github.com/jcmturner/gokrb5/blob/bc57e566151da508625884ff2463482f98301fd5/client/client_integration_test.go#L593

Can you check your setup again?

The only other thing I notice is that the realm of your target service is different to your client user. This may have something to do with it.

Generally I would recommend not having a dependency on the OS level cache and code a more native Go client.

**Comment by dkfitbit** [comment]
Sorry for the long delay, I was out of the office for several months.

For the moment we've abandoned gokrb5, because we encountered too many problems trying to get our version 1 out the door. Namely, this issue plus the fact that MacOS X has a completely different way of storing cached TGTs (which gokrb5 does not currently implement). I still like gokrb5 and will likely recommend it to others for server-side use, as it's the least bad of all the Kerberos libraries I've used in Go, but the fact that it's a ground-up reimplementation instead of a wrapper around the OS-native DSO makes it a hard pill to swallow for using it in a client binary.

"This is not a valid krb5 config"

The actual code uses a much longer configuration or reads a file from disk, depending on flags.  The actual file is two kilobytes and contains private domain names that only resolve on our internal network, so I didn't think pasting it here would be appreciated.  Suffice to say, `[realms]` lists 5 or more kdc's for each of the two realms, and `[domain_realm]` defines a mapping from private domain names to realms.

"Generally I would recommend not having a dependency on the OS level cache and code a more native Go client."

Our purpose for using Kerberos here is as a Single Sign-On provider for a client-side binary: employees need only run `kinit` once per workday to obtain a valid Kerberos ticket, and their browsers / curl / etc are all configured to automatically reuse the cached TGT. If we cannot re-use the existing OS-level ccache, then we have zero use for Kerberos in our software, unfortunately.

**Comment by jcmturner** [comment]
@dkfitbit I think the issue here is that your clients are logging into the CORP.COM domain and getting TGT for that domain and through a trust getting a TGT for the PROD.COM domain within which the serivce resides that you are trying to access. The problem seems to be that the ``NewClientFromCCache`` function is only loading the TGT for the default realm and not others that may be in the cache. I'll take a look at this.

**Comment by jcmturner** [comment]
Actually I'm not sure that what I commented above was the issue. You mentioned in the original post,

> Proximate cause is that encryptAuthenticator in messages/APReq.go has usage values defined for nametype.KRB_NT_PRINCIPAL and for nametype.KRB_NT_SRV_INST, but not for nametype.KRB_NT_SRV_HST. This causes usage to equal 0, which causes EncryptMessage in crypto/rfc3962/encryption.go to use a nil derived key.

There have been some other issues around this part of the codebase that have been addressed in the meantime so I'm wondering if these have also resolved this issue. Are you able to test and confirm from your side?

Thanks.

**Comment by jcmturner** [comment]
@dkfitbit have you been able to try this again? thanks.
